import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,profile:null,catalog:[],collection:new Map(),friendships:[],challenges:[],raisings:[],raisingActions:[],translations:[],translationMap:new Map(),isAdmin:false,schemaReady:true,dexFilter:'all',dexGroup:'all',adminTamaId:null};
const WIKI_API='https://tamagotchi.fandom.com/api.php', WIKI_PAGE='https://tamagotchi.fandom.com/wiki/';
const imageCache=new Map();

function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2800)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function pct(a,b){return b?Math.round(a/b*100):0}
function editionLabel(v){return v==='uni'?'Uni':'Paradise'}
function displayName(t){return t?.name_fr||t?.name||''}
function description(t){return t?.description_fr||t?.description||''}
function conditions(t){return t?.evolution_conditions_fr||t?.evolution_conditions||''}
function groupLabel(t){return t.dlc||t.world||'Base'}
function wikiTitle(t){return ({'Azaratchi':'Azaratchi (2026)'})[t.name]||t.name}
function wikiPageUrl(t){return WIKI_PAGE+encodeURIComponent(wikiTitle(t).replaceAll(' ','_'))}
function tr(cat,key,fallback=key){return state.translationMap.get(`${cat}:${key}`)||fallback}
function cachedImage(t){if(t.image_url)return t.image_url;const key=`${t.edition}:${t.name}`;if(imageCache.has(key))return imageCache.get(key);const s=localStorage.getItem(`tamadex-img:${key}`);if(s&&s!=='-'){imageCache.set(key,s);return s}return null}
function setCachedImage(t,url){const key=`${t.edition}:${t.name}`;imageCache.set(key,url||null);localStorage.setItem(`tamadex-img:${key}`,url||'-')}
function imageStyle(t){const scale=Number(t.image_scale||.84),x=Number(t.image_pos_x??50),y=Number(t.image_pos_y??50);return `--img-scale:${scale};--img-x:${x}%;--img-y:${y}%`}
function tamaImageMarkup(t,extra=''){const url=cachedImage(t);return `<div class="tama-image ${extra}" data-image-tama="${t.id}" style="${imageStyle(t)}">${url?`<img src="${esc(url)}" alt="${esc(displayName(t))}" loading="lazy" referrerpolicy="no-referrer">`:`<span class="placeholder-icon">${t.edition==='paradise'?'🌱':'🥚'}</span><span class="image-loading">illustration…</span>`}</div>`}

async function batchResolveImages({persist=false,showProgress=true}={}){
  const missing=state.catalog.filter(t=>!cachedImage(t));
  if(!missing.length){if(persist&&state.isAdmin)await persistResolvedImages();return}
  const wrap=$('#image-progress'),bar=$('#image-progress-bar');if(showProgress){wrap?.classList.remove('hidden');bar.value=0}
  const chunks=[];for(let i=0;i<missing.length;i+=35)chunks.push(missing.slice(i,i+35));let done=0;
  for(const chunk of chunks){
    try{
      const titles=chunk.map(wikiTitle).join('|');
      const p=new URLSearchParams({action:'query',prop:'pageimages',piprop:'original|thumbnail',titles,pithumbsize:'700',format:'json',origin:'*'});
      const r=await fetch(`${WIKI_API}?${p}`);if(!r.ok)throw new Error(String(r.status));const j=await r.json();
      const pages=Object.values(j?.query?.pages||{});const byTitle=new Map(pages.map(p=>[String(p.title||'').toLowerCase(),p]));
      for(const t of chunk){const page=byTitle.get(wikiTitle(t).toLowerCase());const url=page?.original?.source||page?.thumbnail?.source||null;if(url)setCachedImage(t,url)}
    }catch(e){console.warn('Résolution images',e)}
    done+=chunk.length;if(showProgress)bar.value=Math.round(done/missing.length*100);
  }
  if(showProgress)setTimeout(()=>wrap?.classList.add('hidden'),700);
  renderDex();renderTargets();renderRaisings();
  window.requestIdleCallback?.(()=>preloadResolvedImages());
  if(persist&&state.isAdmin)await persistResolvedImages();
}
async function preloadResolvedImages(){const urls=[...new Set(state.catalog.map(cachedImage).filter(Boolean))];let i=0;async function worker(){while(i<urls.length){const u=urls[i++];await new Promise(res=>{const im=new Image();im.onload=im.onerror=res;im.referrerPolicy='no-referrer';im.src=u})}}await Promise.all(Array.from({length:4},worker))}
async function persistResolvedImages(){const rows=state.catalog.filter(t=>!t.image_url&&cachedImage(t));let saved=0;for(let i=0;i<rows.length;i+=8){await Promise.all(rows.slice(i,i+8).map(async t=>{const url=cachedImage(t);const {error}=await supabase.from('tamagotchis').update({image_url:url,image_source_url:wikiPageUrl(t)}).eq('id',t.id);if(!error){t.image_url=url;saved++}}))}toast(`${saved} illustration${saved>1?'s':''} enregistrée${saved>1?'s':''} ✨`);renderDex()}

function switchAuth(mode){const login=mode==='login';$('#login-form').classList.toggle('hidden',!login);$('#signup-form').classList.toggle('hidden',login);$('#show-login').classList.toggle('active',login);$('#show-signup').classList.toggle('active',!login)}
$('#show-login').onclick=()=>switchAuth('login');$('#show-signup').onclick=()=>switchAuth('signup');
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error)toast(error.message)});
$('#signup-form').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await supabase.auth.signUp({email:$('#signup-email').value.trim(),password:$('#signup-password').value,options:{data:{display_name:$('#signup-name').value.trim()}}});if(error)return toast(error.message);toast(data.session?'Bienvenue dans TamaDex ✨':'Compte créé. Vérifie ton email.')});
$('#logout-btn').onclick=()=>supabase.auth.signOut();

async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',state.user.id).single();state.profile=data||{};$('#welcome-name').textContent=data?.display_name||data?.username||'Collectionneuse';$('#profile-display').textContent=data?.display_name||data?.username||'Mon profil';$('#profile-email').textContent=state.user.email||'';$('#profile-username').value=data?.username||'';$('#profile-name').value=data?.display_name||'';$('#profile-bio').value=data?.bio||'';$('#profile-public').checked=!!data?.collection_public}
async function loadCatalog(){const {data,error}=await supabase.from('tamagotchis').select('*').order('edition').order('name');if(error){toast('Impossible de charger le catalogue.');return}state.catalog=data||[]}
async function loadCollection(){const {data}=await supabase.from('user_tamagotchis').select('*').eq('user_id',state.user.id);state.collection=new Map((data||[]).map(x=>[x.tamagotchi_id,x]))}
async function loadFriendships(){const {data}=await supabase.from('friendships').select('*, requester:profiles!friendships_requester_id_fkey(id,username,display_name), addressee:profiles!friendships_addressee_id_fkey(id,username,display_name)').or(`requester_id.eq.${state.user.id},addressee_id.eq.${state.user.id}`).order('created_at',{ascending:false});state.friendships=data||[]}
async function loadChallenges(){const {data}=await supabase.from('challenges').select('*, target:tamagotchis(name,name_fr,edition), challenge_participants(user_id,status,progress,completed_at)').order('created_at',{ascending:false});state.challenges=data||[]}
async function loadV3(){
  const [admin,translations,raisings,actions]=await Promise.all([
    supabase.from('app_admins').select('user_id').eq('user_id',state.user.id).maybeSingle(),
    supabase.from('app_translations').select('*').order('category').order('key'),
    supabase.from('active_raisings').select('*, target:tamagotchis(*)').eq('user_id',state.user.id).order('started_at',{ascending:false}),
    supabase.from('raising_actions').select('*').eq('user_id',state.user.id).order('created_at',{ascending:true})
  ]);
  if([admin,translations,raisings,actions].some(r=>r.error)){state.schemaReady=false;console.warn('Migration V3 manquante',admin.error||translations.error||raisings.error||actions.error);return}
  state.schemaReady=true;state.isAdmin=!!admin.data;state.translations=translations.data||[];state.translationMap=new Map(state.translations.map(x=>[`${x.category}:${x.key}`,x.value_fr]));state.raisings=raisings.data||[];state.raisingActions=actions.data||[];$('#admin-entry').classList.toggle('hidden',!state.isAdmin)
}

function renderStats(){for(const ed of ['uni','paradise']){const all=state.catalog.filter(t=>t.edition===ed),owned=all.filter(t=>state.collection.get(t.id)?.obtained);$(`#${ed}-count`).textContent=`${owned.length} / ${all.length}`;$(`#${ed}-percent`).textContent=`${pct(owned.length,all.length)} %`}}
function renderTargets(){const list=state.catalog.filter(t=>state.collection.get(t.id)?.target).slice(0,4),el=$('#targets-list');if(!list.length){el.className='card-list empty-state';el.textContent='Aucun objectif pour le moment.';return}el.className='card-list';el.innerHTML=list.map(t=>`<button class="list-card" data-tama="${t.id}">${tamaImageMarkup(t,'mini-tama-image')}<div class="grow"><h3>${esc(displayName(t))}</h3><p>${editionLabel(t.edition)} · ${esc(groupLabel(t))}</p></div><span>🎯</span></button>`).join('')}
function groupOptions(){let base=state.catalog;if(['uni','paradise'].includes(state.dexFilter))base=base.filter(t=>t.edition===state.dexFilter);const vals=[...new Set(base.map(groupLabel).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));$('#dex-group').innerHTML='<option value="all">Toutes les zones / tickets</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(!vals.includes(state.dexGroup))state.dexGroup='all';$('#dex-group').value=state.dexGroup}
function renderDex(){const q=$('#dex-search').value.trim().toLowerCase();let rows=state.catalog.filter(t=>!q||[displayName(t),t.name,t.family,t.world,t.dlc].filter(Boolean).join(' ').toLowerCase().includes(q));if(['uni','paradise'].includes(state.dexFilter))rows=rows.filter(t=>t.edition===state.dexFilter);if(state.dexFilter==='owned')rows=rows.filter(t=>state.collection.get(t.id)?.obtained);if(state.dexFilter==='target')rows=rows.filter(t=>state.collection.get(t.id)?.target);if(state.dexGroup!=='all')rows=rows.filter(t=>groupLabel(t)===state.dexGroup);$('#dex-result-count').textContent=`${rows.length} personnage${rows.length>1?'s':''}`;const el=$('#dex-grid');if(!rows.length){el.innerHTML='<div class="panel empty-big">🥚<h2>Aucun résultat</h2></div>';return}el.innerHTML=rows.map(t=>{const c=state.collection.get(t.id);return `<button class="tama-card ${c?.obtained?'owned':''} ${c?.target?'target':''}" data-tama="${t.id}"><span class="status-dot">${c?.obtained?'✅':c?.target?'🎯':'○'}</span>${tamaImageMarkup(t)}<div class="card-copy"><h3>${esc(displayName(t))}</h3><span class="badge">${editionLabel(t.edition)}</span><span class="group-name">${esc(groupLabel(t))}</span></div></button>`}).join('')}

function renderFriends(){const incoming=state.friendships.filter(f=>f.status==='pending'&&f.addressee_id===state.user.id),accepted=state.friendships.filter(f=>f.status==='accepted'),req=$('#friend-requests'),friends=$('#friends-list');req.className=incoming.length?'card-list':'card-list empty-state';req.innerHTML=incoming.length?incoming.map(f=>`<div class="list-card"><div class="grow"><h3>${esc(f.requester.display_name||f.requester.username||'Collectionneuse')}</h3><p>@${esc(f.requester.username||'sans-pseudo')}</p></div><div class="mini-actions"><button class="icon-btn" data-friend-accept="${f.id}">✓</button><button class="icon-btn" data-friend-decline="${f.id}">×</button></div></div>`).join(''):'Aucune demande.';friends.className=accepted.length?'card-list':'card-list empty-state';friends.innerHTML=accepted.length?accepted.map(f=>{const p=f.requester_id===state.user.id?f.addressee:f.requester;return `<div class="list-card"><div class="grow"><h3>${esc(p.display_name||p.username||'Collectionneuse')}</h3><p>@${esc(p.username||'sans-pseudo')}</p></div><span>💜</span></div>`}).join(''):'Ajoute une amie pour commencer.'}
function challengeCard(c){const progress=(c.challenge_participants||[]).reduce((s,p)=>s+(p.progress||0),0);return `<div class="list-card"><div class="grow"><h3>🏆 ${esc(c.title)}</h3><p>${c.target?`Objectif : ${esc(c.target.name_fr||c.target.name)}`:c.target_count?`${progress} / ${c.target_count}`:esc(c.description||'Défi personnalisé')}</p></div><span class="badge">${esc(c.status)}</span></div>`}
function renderChallenges(){const el=$('#challenges-list');el.className=state.challenges.length?'card-list':'card-list empty-state';el.innerHTML=state.challenges.length?state.challenges.map(challengeCard).join(''):'Aucun défi pour le moment.';const active=state.challenges.filter(c=>c.status==='active').slice(0,3),home=$('#home-challenges');home.className=active.length?'card-list':'card-list empty-state';home.innerHTML=active.length?active.map(challengeCard).join(''):'Pas encore de défi actif.'}

const ACTIONS=[
  ['meal','🍚','Repas'],['special_meal','🍱','Repas spécial'],['snack','🍰','Collation'],['care_error','💔','Erreur de soin'],['game','🎮','Jeu'],['max_needs','❤️','Faim + bonheur max'],['walk','🚶','Promenade Tama'],['arena_win','🏆','Victoire Arène'],['arcade_perfect','🕹️','Score parfait Arcade'],['delivery','🛵','Commande Delivery'],['travel','✈️','Voyage Tama'],['fashion','👗','Tenue Fashion'],['diy','🧵','Accessoire DIY'],['item','🧸','Objet'],['connection','🔗','Connexion'],['medicine','💊','Médicament'],['cleaning','🧹','Nettoyage'],['sleep','😴','Sommeil'],['other','✨','Autre']
];
function relevantActions(t){const raw=conditions(t).toLowerCase();const base=new Set(['meal','special_meal','snack','care_error','game','max_needs','item','other']);const keys=[['walk','walk'],['delivery','delivery'],['arcade','arcade_perfect'],['travel','travel'],['fashion','fashion'],['diy','diy'],['arena','arena_win'],['connexion','connection'],['connecter','connection']];for(const [needle,type] of keys)if(raw.includes(needle))base.add(type);return ACTIONS.filter(a=>base.has(a[0]))}
function actionsForRaising(id){return state.raisingActions.filter(a=>a.raising_id===id)}
function actionCount(id,type){return actionsForRaising(id).filter(a=>a.action_type===type).reduce((s,a)=>s+(a.quantity||1),0)}
function translateFoods(text){return text.split('/').map(s=>{const k=s.trim();return `<span class="food-chip">🍽️ <b>${esc(tr('food',k,k))}</b>${tr('food',k,k)!==k?`<small>${esc(k)}</small>`:''}</span>`}).join('')}
function translatedCondition(raw){let out=raw;const foods=state.translations.filter(x=>x.category==='food'&&x.value_fr).sort((a,b)=>(b.value_en||b.key).length-(a.value_en||a.key).length);for(const f of foods){const source=f.value_en||f.key;out=out.split(source).join(f.value_fr)}return out}
function guideMarkup(t,rid){const raw=conditions(t);if(!raw)return '<p class="muted">Conditions à compléter.</p>';let html='';const fav=raw.match(/privilégier\s*:\s*([^\.]+)/i);if(fav)html+=`<div class="guide-step"><span class="guide-icon">🍽️</span><div><b>À privilégier pendant le stade Kid</b><div class="food-chips">${translateFoods(fav[1])}</div></div></div>`;
  const rules=[];const care=raw.match(/(?:viser\s*:\s*)?(\d+)\s*[–-]\s*(\d+)\s*erreurs? de soin/i)||raw.match(/(?:viser\s*:\s*)?(\d+)\s*erreur de soin/i);const plus=raw.match(/(\d+)\s*erreurs? de soin ou plus/i);const zero=raw.match(/(?:viser\s*:\s*)?0\s*erreur(?: de soin)?/i);const c=actionCount(rid,'care_error');if(care){const min=+care[1],max=+(care[2]||care[1]);rules.push(['💔','Erreurs de soin',`${c} · objectif ${min===max?min:`${min}–${max}`}`,c>=min&&c<=max?'ok':c>max?'bad':'wait'])}else if(plus){const min=+plus[1];rules.push(['💔','Erreurs de soin',`${c} / ${min}+`,c>=min?'ok':'wait'])}else if(zero){rules.push(['💔','Erreurs de soin',`${c} · objectif 0`,c===0?'ok':'bad'])}
  const mappings=[[/au moins (\d+) Tama Walk/i,'walk','🚶','Promenades Tama'],[/au moins (\d+) commandes? Tama Delivery/i,'delivery','🛵','Commandes Tama Delivery'],[/au moins (\d+) scores? parfaits? au Tama Arcade/i,'arcade_perfect','🎮','Scores parfaits Arcade'],[/au moins (\d+) voyages? Tama Travel/i,'travel','✈️','Voyages Tama Travel'],[/au moins (\d+) tenues? Tama Fashion/i,'fashion','👗','Tenues Tama Fashion'],[/au moins (\d+) fois chacun/i,'max_needs','❤️','Faim + bonheur au maximum']];for(const [re,type,icon,label] of mappings){const m=raw.match(re);if(m){const n=+m[1],v=actionCount(rid,type);rules.push([icon,label,`${v} / ${n}`,v>=n?'ok':'wait'])}}if(/accessoire DIY/i.test(raw)){const v=actionCount(rid,'diy');rules.push(['🧵','Accessoire DIY',`${v} / 1`,v>=1?'ok':'wait'])}
  if(rules.length)html+=`<div class="rule-grid">${rules.map(r=>`<div class="rule ${r[3]}"><span>${r[0]}</span><div><b>${esc(r[1])}</b><small>${esc(r[2])}</small></div></div>`).join('')}</div>`;
  html+=`<details class="raw-condition"><summary>Voir la condition complète</summary><p>${esc(translatedCondition(raw))}</p></details>`;return html}
function raisingCard(r){const t=r.target||state.catalog.find(x=>x.id===r.target_tamagotchi_id);if(!t)return'';const defs=relevantActions(t),counts=defs.map(([type,icon,label])=>[type,icon,label,actionCount(r.id,type)]).filter(x=>x[3]>0);return `<article class="raising-card"><div class="raising-head">${tamaImageMarkup(t,'raising-image')}<div class="grow"><span class="badge">${editionLabel(t.edition)}</span><h2>${esc(r.current_tama_name||'Tama actuel')} <span>→</span> ${esc(displayName(t))}</h2><p>${esc(r.device_label||groupLabel(t))}</p></div><button class="icon-btn" data-complete-raising="${r.id}" title="Objectif obtenu">✓</button></div><div class="evolution-guide">${guideMarkup(t,r.id)}</div>${counts.length?`<div class="counter-strip">${counts.map(x=>`<span>${x[1]} ${esc(x[2])} <b>${x[3]}</b></span>`).join('')}</div>`:''}<div class="quick-actions">${defs.map(([type,icon,label])=>`<button data-log-action="${r.id}" data-action-type="${type}"><span>${icon}</span><small>+ ${esc(tr('action',type,label))}</small></button>`).join('')}</div><div class="raising-footer"><button class="text-button" data-tama="${t.id}">Voir la fiche</button><button class="text-button danger-text" data-abandon-raising="${r.id}">Arrêter</button></div></article>`}
function renderRaisings(){const active=state.raisings.filter(r=>r.status==='active'),el=$('#raisings-list'),home=$('#home-raisings');if(!state.schemaReady){el.innerHTML='<article class="panel setup-card"><h2>Migration V3 nécessaire</h2><p>Exécute le fichier <b>tamadex-v3-migration.sql</b> dans Supabase pour activer l’assistant et l’administration.</p></article>';home.textContent='Assistant V3 à activer dans Supabase.';return}el.innerHTML=active.length?active.map(raisingCard).join(''):'<article class="panel empty-big">🌱<h2>Aucun élevage en cours</h2><p class="muted">Démarre un objectif depuis ici ou depuis une fiche Tama.</p></article>';home.className=active.length?'card-list':'card-list empty-state';home.innerHTML=active.length?active.slice(0,2).map(r=>{const t=r.target;return `<button class="list-card" data-nav="raising">${tamaImageMarkup(t,'mini-tama-image')}<div class="grow"><h3>${esc(r.current_tama_name||'En cours')} → ${esc(displayName(t))}</h3><p>${actionCount(r.id,'care_error')} erreur(s) de soin · ${esc(r.device_label||editionLabel(t.edition))}</p></div><span>🌱</span></button>`}).join(''):'Aucun élevage en cours.'}

function renderAdmin(){if(!state.isAdmin)return;const q=$('#admin-tama-search').value.trim().toLowerCase(),rows=state.catalog.filter(t=>!q||[t.name,displayName(t)].join(' ').toLowerCase().includes(q));$('#admin-tama-select').innerHTML=rows.map(t=>`<option value="${t.id}">${esc(displayName(t))} — ${editionLabel(t.edition)}</option>`).join('');if(!state.adminTamaId||!rows.some(t=>t.id===state.adminTamaId))state.adminTamaId=rows[0]?.id||null;if(state.adminTamaId){$('#admin-tama-select').value=state.adminTamaId;fillAdminTama()};renderTranslations()}
function fillAdminTama(){const t=state.catalog.find(x=>x.id===state.adminTamaId);if(!t)return;$('#admin-name-fr').value=t.name_fr||'';$('#admin-description-fr').value=t.description_fr||t.description||'';$('#admin-conditions-fr').value=t.evolution_conditions_fr||t.evolution_conditions||'';$('#admin-image-url').value=t.image_url||cachedImage(t)||'';$('#admin-image-scale').value=Math.round(Number(t.image_scale||.84)*100);$('#admin-image-x').value=t.image_pos_x??50;$('#admin-image-y').value=t.image_pos_y??50;updateAdminPreview()}
function updateAdminPreview(){const t=state.catalog.find(x=>x.id===state.adminTamaId);if(!t)return;const clone={...t,image_url:$('#admin-image-url').value||cachedImage(t),image_scale:Number($('#admin-image-scale').value)/100,image_pos_x:Number($('#admin-image-x').value),image_pos_y:Number($('#admin-image-y').value)};$('#admin-scale-output').textContent=`${$('#admin-image-scale').value} %`;$('#admin-image-preview').innerHTML=`${tamaImageMarkup(clone,'admin-preview-image')}<b>${esc($('#admin-name-fr').value||displayName(t))}</b>`}
function renderTranslations(){if(!state.isAdmin)return;const q=$('#translation-search').value.trim().toLowerCase();const rows=state.translations.filter(x=>!q||[x.key,x.value_en,x.value_fr,x.category].filter(Boolean).join(' ').toLowerCase().includes(q));$('#translation-count').textContent=`${rows.length} entrées`;$('#translations-list').innerHTML=rows.slice(0,120).map(x=>`<div class="translation-row"><span>${x.category==='food'?'🍽️':'✨'}</span><div><b>${esc(x.value_en||x.key)}</b><small>${esc(x.key)}</small></div><input value="${esc(x.value_fr)}" data-translation-id="${x.id}" aria-label="Traduction française" /></div>`).join('')}

function fillSelectors(){const opts=state.catalog.map(t=>`<option value="${t.id}">${esc(displayName(t))} — ${editionLabel(t.edition)}</option>`).join('');$('#challenge-tama').innerHTML=opts;$('#raising-target').innerHTML=opts}
function renderAll(){renderStats();renderTargets();groupOptions();renderDex();renderFriends();renderChallenges();renderRaisings();fillSelectors();if(state.isAdmin)renderAdmin()}
async function bootstrap(){await Promise.all([loadProfile(),loadCatalog(),loadCollection(),loadFriendships()]);await Promise.all([loadChallenges(),loadV3()]);renderAll();setTimeout(()=>batchResolveImages({showProgress:true}),350)}

function nav(page){if(page==='admin'&&!state.isAdmin)return;$$('.page').forEach(x=>x.classList.remove('active'));$(`#page-${page}`)?.classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===page));$('#page-title').textContent=({home:'Accueil',dex:'TamaDex',raising:'Élevage',friends:'Amies',challenges:'Défis',profile:'Profil',admin:'Administration'})[page]||'TamaDex';window.scrollTo({top:0,behavior:'smooth'});if(page==='admin')renderAdmin()}
$('#avatar-button').onclick=()=>nav('profile');
document.addEventListener('click',async e=>{const n=e.target.closest('[data-nav]');if(n){nav(n.dataset.nav);return}const t=e.target.closest('[data-tama]');if(t){openTama(t.dataset.tama);return}const close=e.target.closest('[data-close-dialog]');if(close){document.getElementById(close.dataset.closeDialog).close();return}const log=e.target.closest('[data-log-action]');if(log){await logAction(log.dataset.logAction,log.dataset.actionType);return}const comp=e.target.closest('[data-complete-raising]');if(comp){await completeRaising(comp.dataset.completeRaising);return}const abandon=e.target.closest('[data-abandon-raising]');if(abandon){await abandonRaising(abandon.dataset.abandonRaising);return}const add=e.target.closest('[data-add-friend]');if(add){const {error}=await supabase.from('friendships').insert({requester_id:state.user.id,addressee_id:add.dataset.addFriend});if(error)return toast(error.code==='23505'?'Demande déjà envoyée.':error.message);await loadFriendships();renderFriends();toast('Demande envoyée 💜')}const accept=e.target.closest('[data-friend-accept]');if(accept){await supabase.from('friendships').update({status:'accepted'}).eq('id',accept.dataset.friendAccept);await loadFriendships();renderFriends()}const decline=e.target.closest('[data-friend-decline]');if(decline){await supabase.from('friendships').update({status:'declined'}).eq('id',decline.dataset.friendDecline);await loadFriendships();renderFriends()}});
$('#dex-search').oninput=renderDex;$('#dex-group').onchange=()=>{state.dexGroup=$('#dex-group').value;renderDex()};$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.dexFilter=b.dataset.filter;state.dexGroup='all';groupOptions();renderDex()});

async function upsertCollection(id,patch){const cur=state.collection.get(id)||{user_id:state.user.id,tamagotchi_id:id,obtained:false,favorite:false,target:false};const row={...cur,...patch,user_id:state.user.id,tamagotchi_id:id};['id','created_at','updated_at'].forEach(k=>delete row[k]);const {data,error}=await supabase.from('user_tamagotchis').upsert(row,{onConflict:'user_id,tamagotchi_id'}).select().single();if(error)return toast(error.message);state.collection.set(id,data);renderAll();openTama(id)}
function openTama(id){const t=state.catalog.find(x=>x.id===id);if(!t)return;const c=state.collection.get(id);$('#tama-dialog-content').innerHTML=`<div class="tama-detail-head">${tamaImageMarkup(t,'detail-image')}<p class="eyebrow detail-eyebrow">${editionLabel(t.edition)} · ${esc(groupLabel(t))}</p><h2>${esc(displayName(t))}</h2><div class="detail-tags">${t.stage?`<span class="badge">${esc(t.stage)}</span>`:''}${t.family?`<span class="badge soft">${esc(t.family)}</span>`:''}</div></div><div class="detail-actions"><button id="toggle-owned" class="secondary ${c?.obtained?'active':''}">${c?.obtained?'✅ Obtenu':'○ Je l’ai obtenu'}</button><button id="toggle-target" class="secondary ${c?.target?'active':''}">${c?.target?'🎯 Objectif':'☆ Ajouter aux objectifs'}</button></div><button id="start-from-tama" class="primary full">🌱 Démarrer un élevage vers ${esc(displayName(t))}</button>${conditions(t)?`<div class="detail-block obtain"><h3>🧭 Comment l’obtenir</h3><div class="static-guide">${guideMarkup(t,'__preview__')}</div></div>`:''}${description(t)?`<div class="detail-block"><h3>À propos</h3><p>${esc(description(t))}</p></div>`:''}<a class="wiki-source" href="${wikiPageUrl(t)}" target="_blank" rel="noopener noreferrer">Voir la fiche source ↗</a>`;$('#tama-dialog').showModal();$('#toggle-owned').onclick=()=>upsertCollection(id,{obtained:!c?.obtained,first_obtained_at:!c?.obtained?new Date().toISOString().slice(0,10):c?.first_obtained_at||null});$('#toggle-target').onclick=()=>upsertCollection(id,{target:!c?.target});$('#start-from-tama').onclick=()=>{if(!state.schemaReady)return toast('Exécute d’abord la migration V3 dans Supabase.');$('#tama-dialog').close();$('#raising-target').value=id;$('#raising-dialog').showModal()}}

$('#new-raising-btn').onclick=()=>{if(!state.schemaReady)return toast('Exécute d’abord la migration V3 dans Supabase.');$('#raising-dialog').showModal()};
$('#raising-form').addEventListener('submit',async e=>{e.preventDefault();const {error}=await supabase.from('active_raisings').insert({user_id:state.user.id,target_tamagotchi_id:$('#raising-target').value,current_tama_name:$('#raising-current').value.trim()||null,device_label:$('#raising-device').value.trim()||null});if(error)return toast(error.message);$('#raising-dialog').close();e.target.reset();await loadV3();renderRaisings();toast('Élevage démarré 🌱')});
async function logAction(rid,type){const {error}=await supabase.from('raising_actions').insert({raising_id:rid,user_id:state.user.id,action_type:type,label:tr('action',type,type),quantity:1});if(error)return toast(error.message);const {data}=await supabase.from('raising_actions').select('*').eq('user_id',state.user.id).order('created_at',{ascending:true});state.raisingActions=data||[];renderRaisings()}
async function completeRaising(rid){const r=state.raisings.find(x=>x.id===rid);if(!r)return;await supabase.from('active_raisings').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',rid);await upsertCollection(r.target_tamagotchi_id,{obtained:true,target:false,first_obtained_at:new Date().toISOString().slice(0,10)});await loadV3();renderRaisings();$('#tama-dialog')?.close();toast('Objectif obtenu ! 🎉')}
async function abandonRaising(rid){await supabase.from('active_raisings').update({status:'abandoned',completed_at:new Date().toISOString()}).eq('id',rid);await loadV3();renderRaisings();toast('Élevage archivé')}

$('#profile-form').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await supabase.from('profiles').update({username:$('#profile-username').value.trim()||null,display_name:$('#profile-name').value.trim(),bio:$('#profile-bio').value.trim(),collection_public:$('#profile-public').checked}).eq('id',state.user.id).select().single();if(error)return toast(error.code==='23505'?'Ce pseudo est déjà utilisé.':error.message);state.profile=data;await loadProfile();toast('Profil enregistré ✨')});
$('#friend-search-btn').onclick=async()=>{const q=$('#friend-search').value.trim();if(!q)return;const {data,error}=await supabase.from('profiles').select('id,username,display_name').neq('id',state.user.id).or(`username.eq.${q},display_name.ilike.%${q}%`).limit(10);if(error)return toast(error.message);$('#friend-results').innerHTML=(data||[]).length?data.map(p=>`<div class="list-card"><div class="grow"><h3>${esc(p.display_name||p.username||'Collectionneuse')}</h3><p>@${esc(p.username||'sans-pseudo')}</p></div><button class="icon-btn" data-add-friend="${p.id}">＋</button></div>`).join(''):'<p class="muted">Aucun profil trouvé.</p>'};
$('#new-challenge-btn').onclick=()=>$('#challenge-dialog').showModal();$('#challenge-type').onchange=()=>{const type=$('#challenge-type').value;$('#challenge-tama-wrap').classList.toggle('hidden',type!=='specific_tama');$('#challenge-count-wrap').classList.toggle('hidden',!['collect_count','cooperative_count'].includes(type))};
$('#challenge-form').addEventListener('submit',async e=>{e.preventDefault();const type=$('#challenge-type').value,end=$('#challenge-end').value,payload={creator_id:state.user.id,title:$('#challenge-title').value.trim(),description:$('#challenge-description').value.trim()||null,challenge_type:type,target_tamagotchi_id:type==='specific_tama'?$('#challenge-tama').value:null,target_count:['collect_count','cooperative_count'].includes(type)?Number($('#challenge-count').value):null,ends_at:end?new Date(`${end}T23:59:59`).toISOString():null};const {data,error}=await supabase.from('challenges').insert(payload).select().single();if(error)return toast(error.message);await supabase.from('challenge_participants').insert({challenge_id:data.id,user_id:state.user.id,status:'accepted'});$('#challenge-dialog').close();e.target.reset();await loadChallenges();renderChallenges();toast('Défi créé 🏆')});

$('#admin-tama-search').oninput=renderAdmin;$('#admin-tama-select').onchange=()=>{state.adminTamaId=$('#admin-tama-select').value;fillAdminTama()};['admin-name-fr','admin-image-url','admin-image-scale','admin-image-x','admin-image-y'].forEach(id=>$('#'+id).addEventListener('input',updateAdminPreview));
$('#admin-tama-form').addEventListener('submit',async e=>{e.preventDefault();if(!state.isAdmin)return;const id=state.adminTamaId,payload={name_fr:$('#admin-name-fr').value.trim()||null,description_fr:$('#admin-description-fr').value.trim()||null,evolution_conditions_fr:$('#admin-conditions-fr').value.trim()||null,image_url:$('#admin-image-url').value.trim()||null,image_scale:Number($('#admin-image-scale').value)/100,image_pos_x:Number($('#admin-image-x').value),image_pos_y:Number($('#admin-image-y').value)};const {data,error}=await supabase.from('tamagotchis').update(payload).eq('id',id).select().single();if(error)return toast(error.message);const i=state.catalog.findIndex(t=>t.id===id);state.catalog[i]=data;if(data.image_url)setCachedImage(data,data.image_url);renderAll();toast('Personnage enregistré ✨')});
$('#translation-search').oninput=renderTranslations;$('#translations-list').addEventListener('change',async e=>{const input=e.target.closest('[data-translation-id]');if(!input)return;const row=state.translations.find(x=>x.id===input.dataset.translationId);if(!row)return;const {data,error}=await supabase.from('app_translations').update({value_fr:input.value.trim()}).eq('id',row.id).select().single();if(error)return toast(error.message);Object.assign(row,data);state.translationMap.set(`${row.category}:${row.key}`,row.value_fr);renderRaisings();toast('Traduction enregistrée')});
$('#resolve-images-btn').onclick=async()=>{if(!state.isAdmin)return;toast('Résolution des illustrations…');await batchResolveImages({persist:true,showProgress:true});renderAdmin()};

supabase.auth.onAuthStateChange(async(_event,session)=>{state.user=session?.user||null;if(state.user){$('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');await bootstrap()}else{$('#app-view').classList.add('hidden');$('#auth-view').classList.remove('hidden')}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
