import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,profile:null,catalog:[],collection:new Map(),friendships:[],challenges:[],raisings:[],raisingActions:[],stageEvents:[],evolutionEdges:[],translations:[],translationMap:new Map(),isAdmin:false,schemaReady:true,dexFilter:'all',dexGroup:'all',dexStage:'all',adminTamaId:null};
const WIKI_API='https://tamagotchi.fandom.com/api.php', WIKI_PAGE='https://tamagotchi.fandom.com/wiki/';
const imageCache=new Map();

function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2800)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function pct(a,b){return b?Math.round(a/b*100):0}
function editionLabel(v){return v==='uni'?'Uni':'Paradise'}
function stageLabel(v){return ({baby:'Bébé',child:'Enfant',kid:'Enfant',teen:'Ado',young:'Ado',adult:'Adulte',egg:'Œuf'})[String(v||'').toLowerCase()]||v||'Stade ?'}
function stageKey(v){const x=String(v||'').toLowerCase();return x==='kid'?'child':x==='young'?'teen':x}
function nextStage(v){return ({egg:'baby',baby:'child',child:'teen',teen:'adult'})[stageKey(v)]||null}
function displayName(t){return t?.name_fr||t?.name||''}
function description(t){return t?.description_fr||t?.description||''}
function conditions(t){return t?.evolution_conditions_fr||t?.evolution_conditions||''}
function groupLabel(t){return t.dlc||t.world||'Base'}
function wikiTitle(t){return ({'Azaratchi':'Azaratchi (2026)'})[t.name]||t.name}
function wikiPageUrl(t){return WIKI_PAGE+encodeURIComponent(wikiTitle(t).replaceAll(' ','_'))}
function tr(cat,key,fallback=key){return state.translationMap.get(`${cat}:${key}`)||fallback}
function cachedImage(t){if(t.image_url)return t.image_url;const key=`${t.edition}:${t.name}`;if(imageCache.has(key))return imageCache.get(key);const s=localStorage.getItem(`tamadex-img:${key}`);if(s&&s!=='-'){imageCache.set(key,s);return s}return null}
function setCachedImage(t,url){const key=`${t.edition}:${t.name}`;imageCache.set(key,url||null);localStorage.setItem(`tamadex-img:${key}`,url||'-')}
function imageStyle(t){const scale=Number(t.image_scale||.84),x=Number(t.image_pos_x??50),y=Number(t.image_pos_y??50);return `--img-scale:${scale};--img-x:${x}%;--img-y:${y}%`}
function tamaImageMarkup(t,extra=''){const url=cachedImage(t);return `<div class="tama-image ${extra}" data-image-tama="${t.id}" style="${imageStyle(t)}">${url?`<img src="${esc(url)}" alt="${esc(displayName(t))}" loading="lazy" referrerpolicy="no-referrer">`:`<span class="placeholder-icon">${t.edition==='paradise'?'🌱':'🥚'}</span><span class="image-loading">illustration…</span>`}</div>`}

async function batchResolveImages({persist=false,showProgress=true}={}){
  const missing=state.catalog.filter(t=>!cachedImage(t));
  if(!missing.length){if(persist&&state.isAdmin)await persistResolvedImages();return}
  const wrap=$('#image-progress'),bar=$('#image-progress-bar');if(showProgress){wrap?.classList.remove('hidden');bar.value=0}
  const chunks=[];for(let i=0;i<missing.length;i+=35)chunks.push(missing.slice(i,i+35));let done=0;
  for(const chunk of chunks){
    try{
      const titles=chunk.map(wikiTitle).join('|');
      const p=new URLSearchParams({action:'query',prop:'pageimages',piprop:'original|thumbnail',titles,pithumbsize:'700',format:'json',origin:'*'});
      const r=await fetch(`${WIKI_API}?${p}`);if(!r.ok)throw new Error(String(r.status));const j=await r.json();
      const pages=Object.values(j?.query?.pages||{});const byTitle=new Map(pages.map(p=>[String(p.title||'').toLowerCase(),p]));
      for(const t of chunk){const page=byTitle.get(wikiTitle(t).toLowerCase());const url=page?.original?.source||page?.thumbnail?.source||null;if(url)setCachedImage(t,url)}
    }catch(e){console.warn('Résolution images',e)}
    done+=chunk.length;if(showProgress)bar.value=Math.round(done/missing.length*100);
  }
  if(showProgress)setTimeout(()=>wrap?.classList.add('hidden'),700);
  renderDex();renderTargets();renderRaisings();
  window.requestIdleCallback?.(()=>preloadResolvedImages());
  if(persist&&state.isAdmin)await persistResolvedImages();
}
async function preloadResolvedImages(){const urls=[...new Set(state.catalog.map(cachedImage).filter(Boolean))];let i=0;async function worker(){while(i<urls.length){const u=urls[i++];await new Promise(res=>{const im=new Image();im.onload=im.onerror=res;im.referrerPolicy='no-referrer';im.src=u})}}await Promise.all(Array.from({length:4},worker))}
async function persistResolvedImages(){const rows=state.catalog.filter(t=>!t.image_url&&cachedImage(t));let saved=0;for(let i=0;i<rows.length;i+=8){await Promise.all(rows.slice(i,i+8).map(async t=>{const url=cachedImage(t);const {error}=await supabase.from('tamagotchis').update({image_url:url,image_source_url:wikiPageUrl(t)}).eq('id',t.id);if(!error){t.image_url=url;saved++}}))}toast(`${saved} illustration${saved>1?'s':''} enregistrée${saved>1?'s':''} ✨`);renderDex()}

function switchAuth(mode){const login=mode==='login';$('#login-form').classList.toggle('hidden',!login);$('#signup-form').classList.toggle('hidden',login);$('#show-login').classList.toggle('active',login);$('#show-signup').classList.toggle('active',!login)}
$('#show-login').onclick=()=>switchAuth('login');$('#show-signup').onclick=()=>switchAuth('signup');
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error)toast(error.message)});
$('#signup-form').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await supabase.auth.signUp({email:$('#signup-email').value.trim(),password:$('#signup-password').value,options:{data:{display_name:$('#signup-name').value.trim()}}});if(error)return toast(error.message);toast(data.session?'Bienvenue dans TamaDex ✨':'Compte créé. Vérifie ton email.')});
$('#logout-btn').onclick=()=>supabase.auth.signOut();

async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',state.user.id).single();state.profile=data||{};$('#welcome-name').textContent=data?.display_name||data?.username||'Collectionneuse';$('#profile-display').textContent=data?.display_name||data?.username||'Mon profil';$('#profile-email').textContent=state.user.email||'';$('#profile-username').value=data?.username||'';$('#profile-name').value=data?.display_name||'';$('#profile-bio').value=data?.bio||'';$('#profile-public').checked=!!data?.collection_public}
async function loadCatalog(){const {data,error}=await supabase.from('tamagotchis').select('*').order('edition').order('name');if(error){toast('Impossible de charger le catalogue.');return}state.catalog=data||[]}
async function loadCollection(){const {data}=await supabase.from('user_tamagotchis').select('*').eq('user_id',state.user.id);state.collection=new Map((data||[]).map(x=>[x.tamagotchi_id,x]))}
async function loadFriendships(){const {data}=await supabase.from('friendships').select('*, requester:profiles!friendships_requester_id_fkey(id,username,display_name), addressee:profiles!friendships_addressee_id_fkey(id,username,display_name)').or(`requester_id.eq.${state.user.id},addressee_id.eq.${state.user.id}`).order('created_at',{ascending:false});state.friendships=data||[]}
async function loadChallenges(){const {data}=await supabase.from('challenges').select('*, target:tamagotchis(name,name_fr,edition), challenge_participants(user_id,status,progress,completed_at)').order('created_at',{ascending:false});state.challenges=data||[]}
async function loadV3(){
  const [admin,translations,raisings,actions,stages,edges,v32]=await Promise.all([
    supabase.from('app_admins').select('user_id').eq('user_id',state.user.id).maybeSingle(),
    supabase.from('app_translations').select('*').order('category').order('key'),
    supabase.from('active_raisings').select('*, context, target:tamagotchis!active_raisings_target_tamagotchi_id_fkey(*)').eq('user_id',state.user.id).order('started_at',{ascending:false}),
    supabase.from('raising_actions').select('*').eq('user_id',state.user.id).order('created_at',{ascending:true}),
    supabase.from('raising_stage_events').select('*').eq('user_id',state.user.id).order('created_at',{ascending:true}),
    supabase.from('evolution_edges').select('*'),
    supabase.from('active_raisings').select('id,mode,edition,current_stage,current_tamagotchi_id').limit(1)
  ]);
  if([admin,translations,raisings,actions,stages,edges,v32].some(r=>r.error)){state.schemaReady=false;console.warn('Migration V3.2 manquante',admin.error||translations.error||raisings.error||actions.error||stages.error||v32.error);return}
  state.schemaReady=true;state.isAdmin=!!admin.data;state.translations=translations.data||[];state.translationMap=new Map(state.translations.map(x=>[`${x.category}:${x.key}`,x.value_fr]));state.raisings=raisings.data||[];state.raisingActions=actions.data||[];state.stageEvents=stages.data||[];state.evolutionEdges=edges.data||[];$('#admin-entry').classList.toggle('hidden',!state.isAdmin)
}

function renderStats(){for(const ed of ['uni','paradise']){const all=state.catalog.filter(t=>t.edition===ed&&t.collection_visible!==false),owned=all.filter(t=>state.collection.get(t.id)?.obtained);$(`#${ed}-count`).textContent=`${owned.length} / ${all.length}`;$(`#${ed}-percent`).textContent=`${pct(owned.length,all.length)} %`}}
function renderTargets(){const list=state.catalog.filter(t=>state.collection.get(t.id)?.target).slice(0,4),el=$('#targets-list');if(!list.length){el.className='card-list empty-state';el.textContent='Aucun objectif pour le moment.';return}el.className='card-list';el.innerHTML=list.map(t=>`<button class="list-card" data-tama="${t.id}">${tamaImageMarkup(t,'mini-tama-image')}<div class="grow"><h3>${esc(displayName(t))}</h3><p>${editionLabel(t.edition)} · ${esc(groupLabel(t))}</p></div><span>🎯</span></button>`).join('')}
function groupOptions(){let base=state.catalog;if(['uni','paradise'].includes(state.dexFilter))base=base.filter(t=>t.edition===state.dexFilter);const vals=[...new Set(base.map(groupLabel).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));$('#dex-group').innerHTML='<option value="all">Toutes les zones / tickets</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(!vals.includes(state.dexGroup))state.dexGroup='all';$('#dex-group').value=state.dexGroup}
function renderDex(){const q=$('#dex-search').value.trim().toLowerCase();let rows=state.catalog.filter(t=>t.collection_visible!==false).filter(t=>!q||[displayName(t),t.name,t.family,t.world,t.dlc,t.stage].filter(Boolean).join(' ').toLowerCase().includes(q));if(state.dexStage!=='all')rows=rows.filter(t=>String(t.stage).toLowerCase()===state.dexStage.toLowerCase());if(['uni','paradise'].includes(state.dexFilter))rows=rows.filter(t=>t.edition===state.dexFilter);if(state.dexFilter==='owned')rows=rows.filter(t=>state.collection.get(t.id)?.obtained);if(state.dexFilter==='target')rows=rows.filter(t=>state.collection.get(t.id)?.target);if(state.dexGroup!=='all')rows=rows.filter(t=>groupLabel(t)===state.dexGroup);$('#dex-result-count').textContent=`${rows.length} personnage${rows.length>1?'s':''}`;const el=$('#dex-grid');if(!rows.length){el.innerHTML='<div class="panel empty-big">🥚<h2>Aucun résultat</h2></div>';return}el.innerHTML=rows.map(t=>{const c=state.collection.get(t.id);return `<button class="tama-card ${c?.obtained?'owned':''} ${c?.target?'target':''}" data-tama="${t.id}"><span class="status-dot">${c?.obtained?'✅':c?.target?'🎯':'○'}</span>${tamaImageMarkup(t)}<div class="card-copy"><h3>${esc(displayName(t))}</h3><span class="badge">${editionLabel(t.edition)}</span><span class="stage-badge">${esc(stageLabel(t.stage))}</span><span class="group-name">${esc(groupLabel(t))}</span></div></button>`}).join('')}

function renderFriends(){const incoming=state.friendships.filter(f=>f.status==='pending'&&f.addressee_id===state.user.id),accepted=state.friendships.filter(f=>f.status==='accepted'),req=$('#friend-requests'),friends=$('#friends-list');req.className=incoming.length?'card-list':'card-list empty-state';req.innerHTML=incoming.length?incoming.map(f=>`<div class="list-card"><div class="grow"><h3>${esc(f.requester.display_name||f.requester.username||'Collectionneuse')}</h3><p>@${esc(f.requester.username||'sans-pseudo')}</p></div><div class="mini-actions"><button class="icon-btn" data-friend-accept="${f.id}">✓</button><button class="icon-btn" data-friend-decline="${f.id}">×</button></div></div>`).join(''):'Aucune demande.';friends.className=accepted.length?'card-list':'card-list empty-state';friends.innerHTML=accepted.length?accepted.map(f=>{const p=f.requester_id===state.user.id?f.addressee:f.requester;return `<div class="list-card"><div class="grow"><h3>${esc(p.display_name||p.username||'Collectionneuse')}</h3><p>@${esc(p.username||'sans-pseudo')}</p></div><span>💜</span></div>`}).join(''):'Ajoute une amie pour commencer.'}
function challengeCard(c){const progress=(c.challenge_participants||[]).reduce((s,p)=>s+(p.progress||0),0);return `<div class="list-card"><div class="grow"><h3>🏆 ${esc(c.title)}</h3><p>${c.target?`Objectif : ${esc(c.target.name_fr||c.target.name)}`:c.target_count?`${progress} / ${c.target_count}`:esc(c.description||'Défi personnalisé')}</p></div><span class="badge">${esc(c.status)}</span></div>`}
function renderChallenges(){const el=$('#challenges-list');el.className=state.challenges.length?'card-list':'card-list empty-state';el.innerHTML=state.challenges.length?state.challenges.map(challengeCard).join(''):'Aucun défi pour le moment.';const active=state.challenges.filter(c=>c.status==='active').slice(0,3),home=$('#home-challenges');home.className=active.length?'card-list':'card-list empty-state';home.innerHTML=active.length?active.map(challengeCard).join(''):'Pas encore de défi actif.'}


function renderAdmin(){if(!state.isAdmin)return;const q=$('#admin-tama-search').value.trim().toLowerCase(),rows=state.catalog.filter(t=>!q||[t.name,displayName(t)].join(' ').toLowerCase().includes(q));$('#admin-tama-select').innerHTML=rows.map(t=>`<option value="${t.id}">${esc(displayName(t))} — ${editionLabel(t.edition)}</option>`).join('');if(!state.adminTamaId||!rows.some(t=>t.id===state.adminTamaId))state.adminTamaId=rows[0]?.id||null;if(state.adminTamaId){$('#admin-tama-select').value=state.adminTamaId;fillAdminTama()};renderTranslations()}
function fillAdminTama(){const t=state.catalog.find(x=>x.id===state.adminTamaId);if(!t)return;$('#admin-name-fr').value=t.name_fr||'';$('#admin-description-fr').value=t.description_fr||t.description||'';$('#admin-conditions-fr').value=t.evolution_conditions_fr||t.evolution_conditions||'';$('#admin-rules-json').value=t.evolution_rules?JSON.stringify(t.evolution_rules,null,2):'';$('#admin-rules-source').value=t.rules_source_url||'';$('#admin-rules-verified').checked=!!t.rules_verified;$('#admin-image-url').value=t.image_url||cachedImage(t)||'';$('#admin-image-scale').value=Math.round(Number(t.image_scale||.84)*100);$('#admin-image-x').value=t.image_pos_x??50;$('#admin-image-y').value=t.image_pos_y??50;updateAdminPreview()}
function updateAdminPreview(){const t=state.catalog.find(x=>x.id===state.adminTamaId);if(!t)return;const clone={...t,image_url:$('#admin-image-url').value||cachedImage(t),image_scale:Number($('#admin-image-scale').value)/100,image_pos_x:Number($('#admin-image-x').value),image_pos_y:Number($('#admin-image-y').value)};$('#admin-scale-output').textContent=`${$('#admin-image-scale').value} %`;$('#admin-image-preview').innerHTML=`${tamaImageMarkup(clone,'admin-preview-image')}<b>${esc($('#admin-name-fr').value||displayName(t))}</b>`}
function renderTranslations(){if(!state.isAdmin)return;const q=$('#translation-search').value.trim().toLowerCase();const rows=state.translations.filter(x=>!q||[x.key,x.value_en,x.value_fr,x.category].filter(Boolean).join(' ').toLowerCase().includes(q));$('#translation-count').textContent=`${rows.length} entrées`;$('#translations-list').innerHTML=rows.slice(0,120).map(x=>`<div class="translation-row"><span>${x.category==='food'?'🍽️':'✨'}</span><div><b>${esc(x.value_en||x.key)}</b><small>${esc(x.key)}</small></div><input value="${esc(x.value_fr)}" data-translation-id="${x.id}" aria-label="Traduction française" /></div>`).join('')}

const ACTIONS=[
  ['meal','🍚','Repas'],['special_meal','🍱','Repas spécial'],['snack','🍰','Collation'],['food_meat','🥩','Viande'],['food_carrot','🥕','Carotte / fruits'],['food_worm','🐛','Insectes / vers'],['food_seafood','🐟','Produits de la mer'],['food_seaweed','🌿','Algues'],['food_plankton','🦐','Plancton'],['food_chicken','🍗','Poulet'],['food_corn','🌽','Maïs / cerise'],['food_honey','🍯','Miel / fleurs'],['food_peking','🥟','Viande pékinoise'],['food_bamboo','🎋','Bambou / sésame'],['food_pomegranate','🍎','Grenade / kaki'],['food_tropical_meat','🍔','Viande tropicale'],['food_banana','🍌','Banane / fruits tropicaux'],['food_butterfly','🦋','Papillons / petites bêtes'],['food_frozen_meat','🥶','Viande glacée'],['food_northern_seafood','🐟','Produits de la mer nordiques'],['food_red_berry','🫐','Baies rouges'],['food_default','⚪','Pellets / alimentation mixte'],['care_error','💔','Erreur de soin'],['game','🎮','Jeu'],['max_needs','❤️','Faim + bonheur max'],['walk','🚶','Promenade Tama'],['arena_win','🏆','Victoire Arène'],['arcade_perfect','🕹️','Score parfait Arcade'],['delivery','🛵','Commande Delivery'],['travel','✈️','Voyage Tama'],['fashion','👗','Tenue Tama Fashion'],['diy','🧵','Fabrication DIY'],['item','🧸','Objet utilisé'],['dlc_content','🎟️','Contenu du ticket'],['connection','🔗','Connexion'],['medicine','💊','Médicament'],['cleaning','🧹','Nettoyage'],['sleep','😴','Sommeil'],['other','✨','Autre']
];
const ACTION_MAP=new Map(ACTIONS.map(a=>[a[0],a]));
const actionDef=type=>ACTION_MAP.get(type)||[type,'✨',type];
function currentStageStart(id){const ev=stageEventsFor(id).slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];return ev?.created_at||null}
function actionsForRaising(id,{currentStage=false}={}){let rows=state.raisingActions.filter(a=>a.raising_id===id);if(currentStage){const since=currentStageStart(id);if(since)rows=rows.filter(a=>new Date(a.created_at)>=new Date(since))}return rows}
function actionCount(id,type){if(id==='__preview__')return 0;return actionsForRaising(id,{currentStage:true}).filter(a=>a.action_type===type).reduce((s,a)=>s+(a.quantity||1),0)}
const PARADISE_FOODS=['food_meat','food_carrot','food_worm','food_seafood','food_seaweed','food_plankton','food_chicken','food_corn','food_honey','food_peking','food_bamboo','food_pomegranate','food_tropical_meat','food_banana','food_butterfly','food_frozen_meat','food_northern_seafood','food_red_berry','food_default'];
function paradiseCareCount(id,r){if(raisingEdition(r)!=='paradise')return actionCount(id,'care_error');const events=stageEventsFor(id).slice().sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const child=events.find(e=>stageKey(e.stage)==='child');const since=child?.created_at;return state.raisingActions.filter(a=>a.raising_id===id&&a.action_type==='care_error'&&(!since||new Date(a.created_at)>=new Date(since))).reduce((s,a)=>s+(a.quantity||1),0)}
function paradiseFoodMajority(id,type){const vals=PARADISE_FOODS.map(k=>[k,actionCount(id,k)]),mine=vals.find(x=>x[0]===type)?.[1]||0,max=Math.max(...vals.map(x=>x[1]));if(type==='food_default')return mine>0&&mine===max;return mine>0&&mine===max&&vals.filter(x=>x[1]===max).length===1}

function translateFoods(text){return text.split('/').map(s=>{const k=s.trim();return `<span class="food-chip">🍽️ <b>${esc(tr('food',k,k))}</b>${tr('food',k,k)!==k?`<small>${esc(k)}</small>`:''}</span>`}).join('')}
function translatedCondition(raw){let out=raw;const foods=state.translations.filter(x=>x.category==='food'&&x.value_fr).sort((a,b)=>(b.value_en||b.key).length-(a.value_en||a.key).length);for(const f of foods){const source=f.value_en||f.key;out=out.split(source).join(f.value_fr)}return out}
function actionFromPhrase(s=''){const x=s.toLowerCase();if(x.includes('tama walk'))return'walk';if(x.includes('tama delivery'))return'delivery';if(x.includes('tama arcade')||x.includes('scores parfait'))return'arcade_perfect';if(x.includes('tama travel')||x.includes('voyage'))return'travel';if(x.includes('tama fashion')||x.includes('tenue'))return'fashion';if(x.includes('accessoire diy')||x.includes('fabrication diy'))return'diy';if(x.includes('faim')&&x.includes('bonheur'))return'max_needs';return null}
function reqAction(action,op,value,label,extra={}){const [,icon,def]=actionDef(action);return{kind:'action',action,op,value,icon,label:label||def,...extra}}
function parseCatalogRules(t){
  const raw=conditions(t), model={version:1,generated:true,prerequisites:[],routes:[],advice:[],notes:[]};if(!raw)return model;
  const addPre=(field,op,value,icon,label)=>model.prerequisites.push({id:`${field}-${model.prerequisites.length}`,kind:'context',field,op,value,icon,label});
  const from=raw.match(/Depuis ([^:]+):/i);if(from){const vals=from[1].split(/\s+ou\s+|\s*\/\s*/i).map(x=>x.trim()).filter(Boolean);if(!/n’importe quel ado/i.test(from[1]))addPre('current_tama','one_of',vals,'🌱',`Évoluer depuis ${vals.join(' ou ')}`)}
  const gen=raw.match(/Génération multiple de (\d+)/i);if(gen)addPre('generation','multiple',+gen[1],'🌈',`Génération multiple de ${gen[1]}`);
  if(/mariage dans le Tamaverse/i.test(raw))addPre('marriage_origin','eq','tamaverse','💍','Né(e) d’un mariage au Tama Party / Tamaverse');
  if(/mariage entre deux appareils Uni/i.test(raw))addPre('marriage_origin','eq','uni_connection','🔗','Né(e) d’un mariage entre deux appareils Uni');
  const zone=raw.match(/Activer la zone «([^»]+)»/i);if(zone)addPre('dlc_active','eq',true,'🎟️',`Zone « ${zone[1]} » activée`);
  const field=raw.match(/Champ ([A-Za-zÀ-ÿ]+)/i);if(field)addPre('field','eq',field[1],'🌍',`Champ ${field[1]}`);
  const lineage=raw.match(/lignée ([^\.]+)\./i);if(lineage)addPre('lineage','eq',lineage[1].trim(),'🧬',`Lignée ${lineage[1].trim()}`);
  const fav=raw.match(/privilégier\s*:\s*([^\.]+)/i);if(fav)model.advice.push({kind:'food',icon:'🍽️',label:'À privilégier pendant le stade Kid',value:fav[1]});
  if(/utiliser ou donner le repas, snack ou objet exclusif associé/i.test(raw)){model.routes.push({id:'dlc',label:'Condition du ticket',requirements:[{kind:'context',field:'dlc_dominant',op:'eq',value:true,icon:'🎟️',label:`Utiliser le contenu associé à ${displayName(t)} plus souvent que les autres contenus de la zone`}]});return model}
  const body=(raw.split(':').slice(1).join(':')||raw).trim();
  const alt=body.match(/(0|\d+\s*[–-]\s*\d+)\s*erreurs?(?: de soin)?\s*,?\s*ou\s*(\d+\s*[–-]\s*\d+)\s*erreurs?(?: de soin)?\s*\+\s*au moins\s*(\d+)\s*([^\.]+)/i);
  const parseRange=(txt)=>{if(String(txt).trim()==='0')return{op:'eq',value:0};const m=String(txt).match(/(\d+)\s*[–-]\s*(\d+)/);return m?{op:'between',min:+m[1],max:+m[2]}:null};
  if(alt){const a=parseRange(alt[1]),b=parseRange(alt[2]),act=actionFromPhrase(alt[4]);model.routes.push({id:'route-a',label:'Route A',requirements:[{kind:'action',action:'care_error',icon:'💔',label:'Erreurs de soin',...a}]});const reqs=[{kind:'action',action:'care_error',icon:'💔',label:'Erreurs de soin',...b}];if(act)reqs.push(reqAction(act,'gte',+alt[3]));else model.notes.push(`Condition complémentaire : au moins ${alt[3]} ${alt[4].trim()}`);model.routes.push({id:'route-b',label:'Route B',requirements:reqs});return model}
  const plusCare=body.match(/(\d+)\s*erreurs?(?: de soin)? ou plus/i);const rangeCare=body.match(/(\d+)\s*[–-]\s*(\d+)\s*erreurs?(?: de soin)?/i);const zeroCare=body.match(/(?:viser\s*:\s*)?0\s*erreur(?: de soin)?/i);const reqs=[];
  if(plusCare)reqs.push({kind:'action',action:'care_error',op:'gte',value:+plusCare[1],icon:'💔',label:'Erreurs de soin'});else if(rangeCare)reqs.push({kind:'action',action:'care_error',op:'between',min:+rangeCare[1],max:+rangeCare[2],icon:'💔',label:'Erreurs de soin'});else if(zeroCare)reqs.push({kind:'action',action:'care_error',op:'eq',value:0,icon:'💔',label:'Erreurs de soin'});
  const pats=[[/au moins (\d+) Tama Walk/i,'walk'],[/au moins (\d+) commandes? Tama Delivery/i,'delivery'],[/au moins (\d+) scores? parfaits? au Tama Arcade/i,'arcade_perfect'],[/au moins (\d+) voyages? Tama Travel/i,'travel'],[/au moins (\d+) tenues? Tama Fashion/i,'fashion'],[/au moins (\d+) fois chacun/i,'max_needs']];for(const [re,a] of pats){const m=raw.match(re);if(m)reqs.push(reqAction(a,'gte',+m[1]))}
  if(/accessoire DIY/i.test(raw))reqs.push(reqAction('diy','gte',1,'Fabriquer un accessoire DIY',{stage:'child_teen'}));
  if(reqs.length)model.routes.push({id:'main',label:'Condition à remplir',requirements:reqs});else model.notes.push('Cette condition reste descriptive : consulte le texte complet ci-dessous.');
  return model
}
function rulesFor(t){const r=t?.evolution_rules;if(r&&typeof r==='object')return r;return parseCatalogRules(t)}
function raisingContext(r){return r?.context&&typeof r.context==='object'?r.context:{}}
function evalContext(req,ctx,r){let v=req.field==='current_tama'?(ctx.current_tama||r?.current_tama_name):ctx[req.field];if(v===undefined||v===null||v==='')return'unknown';if(req.op==='eq')return String(v)===String(req.value)?'ok':'bad';if(req.op==='one_of')return req.value.some(x=>String(x).toLowerCase()===String(v).trim().toLowerCase())?'ok':'bad';if(req.op==='multiple'){const n=Number(v);return Number.isFinite(n)&&n>0&&n%Number(req.value)===0?'ok':'bad'}return'unknown'}
function evalAction(req,rid){const n=actionCount(rid,req.action);if(req.op==='eq')return n===Number(req.value)?'ok':n>Number(req.value)?'bad':'wait';if(req.op==='gte')return n>=Number(req.value)?'ok':'wait';if(req.op==='between')return n>Number(req.max)?'bad':n>=Number(req.min)?'ok':'wait';return'wait'}
function reqProgress(req,rid){if(req.kind==='context')return'';const n=actionCount(rid,req.action);if(req.op==='gte')return`${n} / ${req.value}`;if(req.op==='eq')return`${n} · objectif ${req.value}`;if(req.op==='between')return`${n} · objectif ${req.min}–${req.max}`;return String(n)}
function statusFor(t,rid,r){const model=rulesFor(t),ctx=raisingContext(r),pre=(model.prerequisites||[]).map(x=>({...x,status:evalContext(x,ctx,r)}));const routes=(model.routes||[]).map(route=>({...route,requirements:(route.requirements||[]).map(x=>({...x,status:x.kind==='context'?evalContext(x,ctx,r):evalAction(x,rid)}))}));const preBad=pre.some(x=>x.status==='bad'),preUnknown=pre.some(x=>x.status==='unknown'),routeComplete=routes.some(x=>x.requirements.length&&x.requirements.every(y=>y.status==='ok')),allRoutesBad=routes.length&&routes.every(x=>x.requirements.some(y=>y.status==='bad'));let stateName='progress';if(preBad||allRoutesBad)stateName='impossible';else if(preUnknown)stateName='verify';else if(routeComplete)stateName='complete';return{model,pre,routes,state:stateName}}
function statusLabel(s){return s==='complete'?['🟢','Condition remplie']:s==='impossible'?['🔴','Route non accessible']:s==='verify'?['🟠','Prérequis à vérifier']:['🟣','Élevage en cours']}
function ruleCard(req,rid){const icon=req.icon||(req.kind==='action'?actionDef(req.action)[1]:'•'),value=req.kind==='action'?reqProgress(req,rid):(req.status==='ok'?'Confirmé':req.status==='bad'?'Non':'À renseigner');let progress='';if(req.kind==='action'&&req.op==='gte'){const n=actionCount(rid,req.action),max=Math.max(1,Number(req.value));progress=`<progress class="rule-progress" max="${max}" value="${Math.min(n,max)}"></progress>`}return`<div class="rule ${req.status}"><span>${icon}</span><div class="grow"><b>${esc(req.label)}</b><small>${esc(value)}</small>${progress}</div></div>`}
function guideMarkup(t,rid,r=null){const raw=conditions(t);if(!raw)return'<p class="muted">Conditions à compléter.</p>';const s=statusFor(t,rid,r),badge=t.rules_verified?statusLabel(s.state):['🟡','Guide à confirmer'];let html=`<div class="eligibility ${t.rules_verified?s.state:'verify'}"><b>${badge[0]} ${badge[1]}</b>${t.rules_verified?'<span class="verified-pill">✓ règle vérifiée</span>':'<span class="catalog-pill">analyse du catalogue</span>'}</div>`;if(s.pre.length)html+=`<div class="guide-section"><h4>OBLIGATOIRE</h4><div class="rule-grid">${s.pre.map(x=>ruleCard(x,rid)).join('')}</div></div>`;if((s.model.advice||[]).length)html+=`<div class="guide-section"><h4>CONSEIL</h4>${s.model.advice.map(a=>a.kind==='food'?`<div class="guide-step"><span class="guide-icon">${a.icon}</span><div><b>${esc(a.label)}</b><div class="food-chips">${translateFoods(a.value)}</div></div></div>`:`<p>${esc(a.label)}</p>`).join('')}</div>`;if(s.routes.length)html+=`<div class="guide-section"><h4>${s.routes.length>1?'AU CHOIX — une route suffit':'À FAIRE'}</h4><div class="route-list">${s.routes.map((route,i)=>`<div class="route-card ${route.requirements.every(x=>x.status==='ok')?'done':''}">${s.routes.length>1?`<b>${esc(route.label||`Route ${i+1}`)}</b>`:''}<div class="rule-grid">${route.requirements.map(x=>ruleCard(x,rid)).join('')}</div></div>`).join('')}</div></div>`;if((s.model.notes||[]).length)html+=`<div class="guide-note">💡 ${s.model.notes.map(esc).join('<br>')}</div>`;html+=`<details class="raw-condition"><summary>Voir la condition complète</summary><p>${esc(translatedCondition(raw))}</p></details>`;return html}
function requiredActions(t){const m=rulesFor(t),types=[];for(const route of m.routes||[])for(const req of route.requirements||[])if(req.kind==='action'&&req.action&&!types.includes(req.action))types.push(req.action);return ACTIONS.filter(a=>types.includes(a[0]))}
function secondaryActions(t){const primary=new Set(requiredActions(t).map(a=>a[0]));return ACTIONS.filter(a=>['meal','special_meal','snack','care_error','game','max_needs','item','other'].includes(a[0])&&!primary.has(a[0]))}
function contextFieldsFor(t){const model=rulesFor(t),all=[...(model.prerequisites||[]),...(model.routes||[]).flatMap(x=>x.requirements||[])].filter(x=>x.kind==='context'),seen=new Set();return all.filter(x=>x.field!=='current_tama'&&!seen.has(x.field)&&seen.add(x.field))}
function contextInput(req,value=''){const field=req.field;if(field==='generation')return`<label>${esc(req.label)}<input data-context-field="${field}" type="number" min="1" value="${esc(value)}" placeholder="ex. 5" /></label>`;if(field==='sex')return`<label>Sexe du Tama<select data-context-field="sex"><option value="">Je ne sais pas</option><option value="female" ${value==='female'?'selected':''}>Femelle</option><option value="male" ${value==='male'?'selected':''}>Mâle</option></select></label>`;if(field==='marriage_origin')return`<label>Origine de cette génération<select data-context-field="marriage_origin"><option value="">Je ne sais pas</option><option value="tamaverse" ${value==='tamaverse'?'selected':''}>Mariage Tama Party / Tamaverse</option><option value="uni_connection" ${value==='uni_connection'?'selected':''}>Mariage entre deux Uni</option><option value="other" ${value==='other'?'selected':''}>Autre</option></select></label>`;if(field==='dlc_active'||field==='dlc_dominant')return`<label>${esc(req.label)}<select data-context-field="${field}"><option value="">À vérifier</option><option value="true" ${value===true?'selected':''}>Oui</option><option value="false" ${value===false?'selected':''}>Non</option></select></label>`;if(field==='field')return`<label>${esc(req.label)}<select data-context-field="field"><option value="">Je ne sais pas</option>${['Land','Water','Sky','Tropical'].map(x=>`<option value="${x}" ${value===x?'selected':''}>${x}</option>`).join('')}</select></label>`;return`<label>${esc(req.label)}<input data-context-field="${field}" type="text" value="${esc(value)}" /></label>`}
function renderRaisingContextForm(t,ctx={}){const fields=contextFieldsFor(t),wrap=$('#raising-context-fields');wrap.innerHTML=fields.length?`<div class="context-callout"><b>🔎 Vérification d’éligibilité</b><p>TamaDex te demande seulement les informations utiles pour ${esc(displayName(t))}.</p></div>${fields.map(f=>contextInput(f,ctx[f.field])).join('')}`:'<div class="context-callout"><b>ℹ️ Pas de prérequis supplémentaire détecté</b><p>Les actions importantes seront suivies après le démarrage.</p></div>'}
function collectContext(){const ctx={};$$('#raising-context-fields [data-context-field]').forEach(el=>{let v=el.value;if(v==='')return;if(v==='true')v=true;if(v==='false')v=false;if(el.type==='number')v=Number(v);ctx[el.dataset.contextField]=v});ctx.current_tama=$('#raising-current').value.trim()||ctx.current_tama||null;return ctx}
function openRaisingDialog(tid=null,r=null){$('#raising-dialog-title').textContent=r?'🔎 Vérifier mon élevage':'🎯 Élevage avec objectif';$('#raising-id').value=r?.id||'';if(tid||r?.target_tamagotchi_id)$('#raising-target').value=tid||r.target_tamagotchi_id;$('#raising-target').disabled=!!r;$('#raising-current').value=r?.current_tama_name||'';$('#raising-device').value=r?.device_label||'';const t=state.catalog.find(x=>x.id===$('#raising-target').value);if(t)renderRaisingContextForm(t,raisingContext(r));$('#raising-dialog').showModal()}
function whereAmIMarkup(t,rid,r){const s=statusFor(t,rid,r),lab=t.rules_verified?statusLabel(s.state):['🟡','Guide à confirmer'];const missing=[];for(const x of s.pre)if(x.status!=='ok')missing.push(`${x.icon||'•'} ${x.label} : ${x.status==='bad'?'non compatible':'à renseigner'}`);for(const route of s.routes){const todo=route.requirements.filter(x=>x.status!=='ok'&&x.status!=='bad');if(todo.length)missing.push(`${route.label||'Route'} : ${todo.map(x=>x.kind==='action'?`${x.label} (${reqProgress(x,rid)})`:x.label).join(', ')}`)}return`<details class="where-am-i"><summary>🧭 Où j’en suis ?</summary><div><b>${lab[0]} ${lab[1]}</b>${missing.length?`<p>${missing.map(esc).join('<br>')}</p>`:'<p>Toutes les conditions suivies sont remplies.</p>'}${s.state==='verify'?`<button class="secondary full" data-edit-raising="${r.id}">Renseigner les prérequis</button>`:''}</div></details>`}
function stageEventsFor(id){return state.stageEvents.filter(x=>x.raising_id===id)}
function raisingEdition(r){return r.edition||r.target?.edition||'uni'}
function currentTama(r){return state.catalog.find(t=>t.id===r.current_tamagotchi_id)||state.catalog.find(t=>t.edition===raisingEdition(r)&&[t.name,t.name_fr].filter(Boolean).some(n=>String(n).toLowerCase()===String(r.current_tama_name||'').toLowerCase()))||null}
function discoveryCandidates(r){const ed=raisingEdition(r),cur=currentTama(r),stage=stageKey(r.current_stage||cur?.stage||'egg'),next=nextStage(stage);if(!next)return{verified:[],unknown:[],total:0};const direct=cur?state.evolutionEdges.filter(e=>e.edition===ed&&e.from_tamagotchi_id===cur.id):[];if(direct.length){const verified=direct.filter(e=>e.verified).map(e=>({t:state.catalog.find(t=>t.id===e.to_tamagotchi_id),status:'possible',note:e.rule_note,edge:e})).filter(x=>x.t);const unknown=direct.filter(e=>!e.verified).map(e=>state.catalog.find(t=>t.id===e.to_tamagotchi_id)).filter(Boolean);return{verified,unknown,total:direct.length,direct:true}}const same=state.catalog.filter(t=>t.edition===ed&&stageKey(t.stage)===next),sex=raisingContext(r).sex;const filtered=sex&&ed==='uni'?same.filter(t=>!t.gender||t.gender===sex):same;return{verified:[],unknown:filtered,total:filtered.length,direct:false}}
function parseCareRange(text=''){let m=String(text).match(/(\d+)\s*[–-]\s*(\d+)\s*erreurs?/i);if(m)return{min:+m[1],max:+m[2]};m=String(text).match(/(\d+)\+\s*erreurs?/i);if(m)return{min:+m[1],max:99};m=String(text).match(/(\d+)\s*erreurs?/i);if(m)return{min:+m[1],max:+m[1]};return null}
function branchConditionModel(note=''){
  const raw=String(note||''), out={routes:[],text:raw};
  const parts=raw.split(/\s*,?\s+ou\s+/i).map(x=>x.trim()).filter(Boolean);
  for(const part of (parts.length?parts:[raw])){
    const route={happiness:null,care:null,actions:[],context:[],text:part};let m;
    m=part.match(/bonheur\s*(?:entre\s*)?(\d+)\s*(?:à|–|-)\s*(\d+)/i);if(m)route.happiness={min:+m[1],max:+m[2]};
    route.care=parseCareRange(part);
    const pats=[[/([0-9]+)\s*(?:promenades?|Tama Walk)/i,'walk'],[/([0-9]+)\s*(?:commandes? Tama Delivery)/i,'delivery'],[/([0-9]+)\s*(?:scores? parfaits?)/i,'arcade_perfect'],[/([0-9]+)\s*(?:tenues? Tama Fashion)/i,'fashion'],[/([0-9]+)\s*(?:DIY|fabrications? DIY)/i,'diy'],[/([0-9]+)\s*(?:collations?|snacks?)/i,'snack'],[/([0-9]+)\s*(?:voyages? Tama Travel|voyages?)/i,'travel']];
    for(const [re,type] of pats){const x=part.match(re);if(x)route.actions.push({type,goal:+x[1]})}
    if(/génération multiple de 5/i.test(part))route.context.push({type:'generation5',label:'Génération multiple de 5'});
    if(/mariage Tamaverse/i.test(part))route.context.push({type:'tamaverse',label:'Mariage Tamaverse'});
    if(/mariage entre deux Uni|né[e]? d.un mariage entre deux Uni/i.test(part))route.context.push({type:'uni_marriage',label:'Mariage entre deux Uni'});
    if(/majorité viande/i.test(part))route.food={type:'food_meat',label:'Viande'};if(/majorité carotte/i.test(part))route.food={type:'food_carrot',label:'Carotte'};if(/majorité insectes/i.test(part))route.food={type:'food_worm',label:'Insectes'};if(/majorité produits\ de\ la\ mer/i.test(part))route.food={type:'food_seafood',label:'Produits De La Mer'};if(/majorité algues/i.test(part))route.food={type:'food_seaweed',label:'Algues'};if(/majorité plancton/i.test(part))route.food={type:'food_plankton',label:'Plancton'};if(/majorité poulet/i.test(part))route.food={type:'food_chicken',label:'Poulet'};if(/majorité maïs/i.test(part))route.food={type:'food_corn',label:'Maïs'};if(/majorité miel/i.test(part))route.food={type:'food_honey',label:'Miel'};if(/majorité viande\ pékinoise/i.test(part))route.food={type:'food_peking',label:'Viande Pékinoise'};if(/majorité bambou/i.test(part))route.food={type:'food_bamboo',label:'Bambou'};if(/majorité grenade/i.test(part))route.food={type:'food_pomegranate',label:'Grenade'};if(/majorité viande\ tropicale/i.test(part))route.food={type:'food_tropical_meat',label:'Viande Tropicale'};if(/majorité banane/i.test(part))route.food={type:'food_banana',label:'Banane'};if(/majorité papillons/i.test(part))route.food={type:'food_butterfly',label:'Papillons'};if(/majorité viande\ glacée/i.test(part))route.food={type:'food_frozen_meat',label:'Viande Glacée'};if(/majorité produits\ de\ la\ mer\ nordiques/i.test(part))route.food={type:'food_northern_seafood',label:'Produits De La Mer Nordiques'};if(/majorité baies\ rouges/i.test(part))route.food={type:'food_red_berry',label:'Baies Rouges'};if(/majorité pellets\ /\ mixte/i.test(part))route.food={type:'food_default',label:'Pellets / Mixte'};
    const fm=part.match(/Champ (Terre|Eau|Ciel|Forêt|Tropical|Glace)/i);if(fm){const map={Terre:'Land',Eau:'Water',Ciel:'Sky','Forêt':'Forest',Tropical:'Tropical',Glace:'Ice'};route.context.push({type:'field',value:map[fm[1]]||fm[1],label:`Champ ${fm[1]}`})}
    if(/deux couleurs|deux versions/i.test(part))route.actions.push({type:'connection',goal:2});
    const maxm=part.match(/faim et bonheur au maximum.*?(\d+) fois/i);if(maxm)route.actions.push({type:'max_needs',goal:+maxm[1]});
    out.routes.push(route)
  }return out
}
function routeState(route,rid,r){const ctx=raisingContext(r),hp=Number(ctx.happiness_points),care=paradiseCareCount(rid,r);const checks=[];
  if(route.happiness)checks.push(Number.isFinite(hp)&&hp>=route.happiness.min&&hp<=route.happiness.max);
  if(route.care)checks.push(care>=route.care.min&&care<=route.care.max);
  for(const a of route.actions)checks.push(actionCount(rid,a.type)>=a.goal);
  if(route.food)checks.push(paradiseFoodMajority(rid,route.food.type));
  for(const c of route.context){if(c.type==='generation5')checks.push(Number(ctx.generation)>0&&Number(ctx.generation)%5===0);if(c.type==='tamaverse')checks.push(ctx.marriage_origin==='tamaverse');if(c.type==='uni_marriage')checks.push(ctx.marriage_origin==='uni');if(c.type==='field')checks.push(ctx.field===c.value)}
  return checks.length&&checks.every(Boolean)
}
function routeMarkup(route,rid,r){const ctx=raisingContext(r),hp=Number(ctx.happiness_points),care=paradiseCareCount(rid,r),bits=[];
  if(route.happiness){const ok=Number.isFinite(hp)&&hp>=route.happiness.min&&hp<=route.happiness.max;bits.push(`<span class="condition-chip ${ok?'ok':''}">❤️ Bonheur ${route.happiness.min}–${route.happiness.max}</span>`)}
  if(route.care){const ok=care>=route.care.min&&care<=route.care.max,label=route.care.max>=99?`${route.care.min}+`:(route.care.min===route.care.max?route.care.min:`${route.care.min}–${route.care.max}`);bits.push(`<span class="condition-chip ${ok?'ok':''}">💔 Erreurs de soin ${care} · cible ${label}</span>`)}
  for(const a of route.actions){const n=actionCount(rid,a.type),d=actionDef(a.type);bits.push(`<span class="condition-chip ${n>=a.goal?'ok':''}">${d[1]} ${esc(tr('action',a.type,d[2]))} ${n}/${a.goal}</span>`)}
  if(route.food){const n=actionCount(rid,route.food.type),ok=paradiseFoodMajority(rid,route.food.type),d=actionDef(route.food.type);bits.push(`<span class=\"condition-chip ${ok?'ok':''}\">${d[1]} Majorité ${esc(route.food.label)} · ${n}</span>`) }
  for(const c of route.context){let ok=false;if(c.type==='generation5')ok=Number(ctx.generation)>0&&Number(ctx.generation)%5===0;if(c.type==='tamaverse')ok=ctx.marriage_origin==='tamaverse';if(c.type==='uni_marriage')ok=ctx.marriage_origin==='uni';if(c.type==='field')ok=ctx.field===c.value;bits.push(`<span class="condition-chip ${ok?'ok':''}">${ok?'✓':'○'} ${esc(c.label)}</span>`)}
  return `<div class="condition-route ${routeState(route,rid,r)?'complete':''}">${bits.join('')||`<span class="condition-chip neutral">📋 ${esc(route.text)}</span>`}</div>`
}
function branchConditionMarkup(edge,rid,r){const m=branchConditionModel(edge.rule_note),routes=m.routes||[];const complete=routes.some(x=>routeState(x,rid,r));return `${routes.map((x,i)=>`${i?'<span class="or-label">OU</span>':''}${routeMarkup(x,rid,r)}`).join('')}${complete?'<div class="condition-met">✓ Condition actuellement remplie</div>':''}`}
function relevantStageActions(r){const c=discoveryCandidates(r),seen=new Map();for(const x of c.verified){const m=branchConditionModel(x.edge?.rule_note||x.note);for(const route of m.routes){for(const a of route.actions)seen.set(a.type,a);if(route.food)seen.set(route.food.type,{type:route.food.type,goal:null});if(route.care&&!seen.has('care_error'))seen.set('care_error',{type:'care_error',goal:null})}}return [...seen.values()]}
function stageTrackingMarkup(r){const cur=currentTama(r),stage=stageKey(r.current_stage||cur?.stage||'egg');if(stage==='egg')return'';const acts=relevantStageActions(r),ctx=raisingContext(r),hp=ctx.happiness_points,c=discoveryCandidates(r);const needsHappiness=c.verified.some(x=>(branchConditionModel(x.edge?.rule_note||x.note).routes||[]).some(rt=>rt.happiness));
  const paradise=raisingEdition(r)==='paradise',needsField=paradise&&['baby','child'].includes(stage);const fieldMarkup=needsField?`<div class="happiness-tracker"><span>🌍 Champ actuel</span><div class="happiness-choices field-choices">${[['Land','🌿 Terre'],['Water','🌊 Eau'],['Sky','☁️ Ciel'],['Forest','🌲 Forêt'],['Tropical','🌺 Tropical'],['Ice','❄️ Glace']].map(([v,l])=>`<button class="${ctx.field===v?'active':''}" data-set-field="${r.id}" data-field="${v}">${l}</button>`).join('')}</div></div>`:'';return `<section class="stage-tracking"><div class="tracking-head"><div><b>🎯 Ce qui influence sa prochaine évolution</b><p>${paradise?'Sur Paradise, le champ, l’alimentation et les erreurs de soin construisent la branche. Les erreurs de soin restent cumulées depuis le stade Enfant.':`Les compteurs ci-dessous concernent uniquement ${cur?esc(displayName(cur)):'ce stade'} et repartiront à zéro à la prochaine évolution.`}</p></div></div>${fieldMarkup}${needsHappiness?`<div class="happiness-tracker"><span>❤️ Bonheur actuel</span><div class="happiness-choices">${[[2,'0–5'],[10,'6–14'],[18,'15–20']].map(([v,l])=>`<button class="${Number(hp)===v?'active':''}" data-set-happiness="${r.id}" data-happiness="${v}">${l}</button>`).join('')}</div></div>`:''}${acts.length?`<div class="useful-actions">${acts.map(a=>{const d=actionDef(a.type),n=actionCount(r.id,a.type);return`<button data-log-action="${r.id}" data-action-type="${a.type}"><span>${d[1]}</span><b>+1 ${esc(tr('action',a.type,d[2]))}</b><small>${n} pour ce stade</small></button>`}).join('')}</div>`:''}<details class="secondary-actions"><summary>＋ Noter un autre événement</summary><div class="quick-actions">${ACTIONS.filter(a=>!acts.some(x=>x.type===a[0])).map(([type,icon,label])=>`<button data-log-action="${r.id}" data-action-type="${type}"><span>${icon}</span><small>+ ${esc(tr('action',type,label))}</small></button>`).join('')}</div></details></section>`}
function possibilityMarkup(r){const c=discoveryCandidates(r),cur=currentTama(r),stage=stageKey(r.current_stage||cur?.stage||'egg'),next=nextStage(stage);if(!next)return'';const title=cur?`Depuis ${displayName(cur)} → ${stageLabel(next)}`:`Prochain stade : ${stageLabel(next)}`;return`<details class="possibilities" open><summary>🔮 ${esc(title)} <span>${c.verified.length?`${c.verified.length} branche${c.verified.length>1?'s':''} vérifiée${c.verified.length>1?'s':''}`:`${c.unknown.length} candidat${c.unknown.length>1?'s':''}`}</span></summary><div class="possibility-body"><p class="tiny muted">${c.direct?'Voici les évolutions documentées depuis ton Tama actuel. Les conditions se mettent à jour avec ton suivi.':'La branche précédente n’est pas encore entièrement documentée.'}</p>${c.verified.length?`<div class="candidate-grid">${c.verified.map(x=>`<div class="candidate-static">${tamaImageMarkup(x.t,'candidate-image')}<div class="candidate-info"><b>${esc(displayName(x.t))}</b><span>${stageLabel(x.t.stage)}${x.t.gender?` · ${x.t.gender==='female'?'♀':'♂'}`:''}</span><div class="branch-conditions">${branchConditionMarkup(x.edge||{rule_note:x.note},r.id,r)}</div></div></div>`).join('')}</div>`:''}${c.unknown.length&&!c.verified.length?`<p class="muted">${c.unknown.length} possibilité${c.unknown.length>1?'s':''} encore à confirmer pour cette branche.</p>`:''}</div></details>`}
function timelineMarkup(r){const stages=stageEventsFor(r.id).map(x=>({date:x.created_at,icon:x.stage==='egg'?'🥚':'🌱',text:`Évolution → ${x.tama_name}${x.stage?` (${stageLabel(x.stage)})`:''}`}));const acts=actionsForRaising(r.id).map(x=>{const d=actionDef(x.action_type);return{date:x.created_at,icon:d[1],text:`${tr('action',x.action_type,d[2])}${x.quantity>1?` ×${x.quantity}`:''}`}});const all=[...stages,...acts].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,10);return`<details class="raising-timeline"><summary>🕐 Chronologie <span>${stages.length+acts.length} événement${stages.length+acts.length>1?'s':''}</span></summary><div>${all.length?all.map(x=>`<div class="timeline-row"><span>${x.icon}</span><div><b>${esc(x.text)}</b><small>${new Date(x.date).toLocaleString('fr-FR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div></div>`).join(''):'<p class="muted">Le journal commencera avec la première action ou évolution.</p>'}</div></details>`}
function discoveryCard(r){const ed=raisingEdition(r),ctx=raisingContext(r),cur=currentTama(r),stage=stageKey(r.current_stage||cur?.stage||'egg'),avatar=cur?tamaImageMarkup(cur,'raising-image'):'<div class="egg-avatar">🥚</div>',title=cur?displayName(cur):(r.current_tama_name||'Œuf en cours');return`<article class="raising-card discovery-card"><div class="raising-head">${avatar}<div class="grow"><span class="badge">${editionLabel(ed)}</span><h2>${esc(title)} <span>→</span> ?</h2><p>${esc(stageLabel(stage))} · ${esc(r.device_label||editionLabel(ed))}${ctx.generation?` · Génération ${esc(ctx.generation)}`:''}</p></div></div><div class="discovery-status"><b>${stage==='egg'?'🥚':'🌱'} Mode découverte</b><p>${cur?`TamaDex connaît maintenant ${esc(displayName(cur))} et ne propose que son prochain stade compatible.`:'À chaque évolution, choisis visuellement le Tama que tu as sous les yeux.'}</p></div>${possibilityMarkup(r)}${stageTrackingMarkup(r)}<button class="evolved-button" data-evolved-raising="${r.id}">${stage==='egg'?'🐣 Mon œuf a éclos':'✨ Mon Tama a évolué'}</button>${timelineMarkup(r)}<div class="raising-footer discovery-footer"><button class="text-button" data-edit-egg="${r.id}">⚙️ Infos de l’œuf</button><button class="text-button" data-pick-target="${r.id}">🎯 Objectif</button><button class="text-button danger-text" data-abandon-raising="${r.id}">Arrêter</button></div></article>`}
function targetCard(r){const t=r.target||state.catalog.find(x=>x.id===r.target_tamagotchi_id);if(!t)return discoveryCard(r);const primary=requiredActions(t),secondary=secondaryActions(t),s=statusFor(t,r.id,r);return`<article class="raising-card"><div class="raising-head">${tamaImageMarkup(t,'raising-image')}<div class="grow"><span class="badge">${editionLabel(t.edition)}</span><h2>${esc(r.current_tama_name||'Tama actuel')} <span>→</span> ${esc(displayName(t))}</h2><p>${esc(r.device_label||groupLabel(t))}</p></div></div><div class="evolution-guide">${guideMarkup(t,r.id,r)}</div>${whereAmIMarkup(t,r.id,r)}${primary.length?`<div class="primary-actions"><p class="action-title">Actions importantes</p><div class="quick-actions important">${primary.map(([type,icon,label])=>`<button data-log-action="${r.id}" data-action-type="${type}"><span>${icon}</span><small>+ ${esc(tr('action',type,label))}</small></button>`).join('')}</div></div>`:''}<details class="secondary-actions"><summary>Autres actions</summary><div class="quick-actions">${secondary.map(([type,icon,label])=>`<button data-log-action="${r.id}" data-action-type="${type}"><span>${icon}</span><small>+ ${esc(tr('action',type,label))}</small></button>`).join('')}</div></details><button class="evolved-button" data-evolved-raising="${r.id}">✨ Mon Tama a évolué</button><button class="obtained-button ${s.state==='complete'?'ready':''}" data-complete-raising="${r.id}">✨ J’ai obtenu ${esc(displayName(t))}</button>${timelineMarkup(r)}<div class="raising-footer"><button class="text-button" data-tama="${t.id}">Voir la fiche</button><button class="text-button danger-text" data-abandon-raising="${r.id}">Arrêter</button></div></article>`}
function raisingCard(r){return r.mode==='discovery'||!r.target_tamagotchi_id?discoveryCard(r):targetCard(r)}
function renderRaisings(){const active=state.raisings.filter(r=>r.status==='active'),el=$('#raisings-list'),home=$('#home-raisings');if(!state.schemaReady){el.innerHTML='<article class="panel setup-card"><h2>Migration V3.3 nécessaire</h2><p>Exécute le fichier <b>tamadex-v3.3-migration.sql</b> dans Supabase pour activer l’élevage depuis l’œuf.</p></article>';home.textContent='Assistant V3.3 à activer dans Supabase.';return}el.innerHTML=active.length?active.map(raisingCard).join(''):'<article class="panel empty-big">🌱<h2>Aucun élevage en cours</h2><p class="muted">Démarre dès l’œuf, ou choisis directement un adulte objectif.</p></article>';home.className=active.length?'card-list':'card-list empty-state';home.innerHTML=active.length?active.slice(0,2).map(r=>{if(r.mode==='discovery'||!r.target_tamagotchi_id)return`<button class="list-card" data-nav="raising"><div class="mini-egg">🥚</div><div class="grow"><h3>${esc(r.current_tama_name||'Œuf')} → ?</h3><p>🔮 Mode découverte · ${esc(r.device_label||editionLabel(raisingEdition(r)))}</p></div><span>🌱</span></button>`;const t=r.target,s=statusFor(t,r.id,r),lab=t.rules_verified?statusLabel(s.state):['🟡','Guide à confirmer'];return`<button class="list-card" data-nav="raising">${tamaImageMarkup(t,'mini-tama-image')}<div class="grow"><h3>${esc(r.current_tama_name||'En cours')} → ${esc(displayName(t))}</h3><p>${lab[0]} ${esc(lab[1])} · ${esc(r.device_label||editionLabel(t.edition))}</p></div><span>🌱</span></button>`}).join(''):'Aucun élevage en cours.'}
function fillSelectors(){const opts=state.catalog.map(t=>`<option value="${t.id}">${esc(displayName(t))} — ${editionLabel(t.edition)}</option>`).join('');$('#challenge-tama').innerHTML=opts;$('#raising-target').innerHTML=opts;$('#pick-target-select').innerHTML=opts}
function renderAll(){renderStats();renderTargets();groupOptions();renderDex();renderFriends();renderChallenges();renderRaisings();fillSelectors();if(state.isAdmin)renderAdmin()}
function nav(page){if(page==='admin'&&!state.isAdmin)return;$$('.page').forEach(x=>x.classList.remove('active'));$(`#page-${page}`)?.classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===page));$('#page-title').textContent=({home:'Accueil',dex:'TamaDex',raising:'Élevage',friends:'Amies',challenges:'Défis',profile:'Profil',admin:'Administration'})[page]||'TamaDex';window.scrollTo({top:0,behavior:'smooth'});if(page==='admin')renderAdmin()}

document.addEventListener('click',async e=>{const n=e.target.closest('[data-nav]');if(n){nav(n.dataset.nav);return}const t=e.target.closest('[data-tama]');if(t){openTama(t.dataset.tama);return}const choice=e.target.closest('[data-evolution-choice]');if(choice){const tama=state.catalog.find(t=>t.id===choice.dataset.evolutionChoice);if(tama)await recordEvolution(choice.dataset.raisingId,tama);return}const close=e.target.closest('[data-close-dialog]');if(close){document.getElementById(close.dataset.closeDialog).close();return}const hp=e.target.closest('[data-set-happiness]');if(hp){await setHappiness(hp.dataset.setHappiness,Number(hp.dataset.happiness));return}const fld=e.target.closest('[data-set-field]');if(fld){await setField(fld.dataset.setField,fld.dataset.field);return}const log=e.target.closest('[data-log-action]');if(log){await logAction(log.dataset.logAction,log.dataset.actionType);return}const comp=e.target.closest('[data-complete-raising]');if(comp){await completeRaising(comp.dataset.completeRaising);return}const abandon=e.target.closest('[data-abandon-raising]');if(abandon){await abandonRaising(abandon.dataset.abandonRaising);return}const edit=e.target.closest('[data-edit-raising]');if(edit){const r=state.raisings.find(x=>x.id===edit.dataset.editRaising);if(r)openRaisingDialog(null,r);return}const evolved=e.target.closest('[data-evolved-raising]');if(evolved){openEvolutionDialog(evolved.dataset.evolvedRaising);return}const eggEdit=e.target.closest('[data-edit-egg]');if(eggEdit){openEggDialog(eggEdit.dataset.editEgg);return}const pick=e.target.closest('[data-pick-target]');if(pick){openPickTarget(pick.dataset.pickTarget);return}const choose=e.target.closest('[data-choose-target]');if(choose){await chooseTarget(choose.dataset.raisingId,choose.dataset.chooseTarget);return}const mode=e.target.closest('[data-start-mode]');if(mode){$('#raising-mode-dialog').close();mode.dataset.startMode==='egg'?openEggDialog():openRaisingDialog();return}const add=e.target.closest('[data-add-friend]');if(add){const {error}=await supabase.from('friendships').insert({requester_id:state.user.id,addressee_id:add.dataset.addFriend});if(error)return toast(error.code==='23505'?'Demande déjà envoyée.':error.message);await loadFriendships();renderFriends();toast('Demande envoyée 💜')}const accept=e.target.closest('[data-friend-accept]');if(accept){await supabase.from('friendships').update({status:'accepted'}).eq('id',accept.dataset.friendAccept);await loadFriendships();renderFriends()}const decline=e.target.closest('[data-friend-decline]');if(decline){await supabase.from('friendships').update({status:'declined'}).eq('id',decline.dataset.friendDecline);await loadFriendships();renderFriends()}});


async function bootstrap(){await Promise.all([loadProfile(),loadCatalog(),loadCollection(),loadFriendships()]);await Promise.all([loadChallenges(),loadV3()]);renderAll();setTimeout(()=>batchResolveImages({showProgress:true}),350)}
$('#avatar-button').onclick=()=>nav('profile');
$('#dex-search').oninput=renderDex;$('#dex-group').onchange=()=>{state.dexGroup=$('#dex-group').value;renderDex()};$('#dex-stage').onchange=()=>{state.dexStage=$('#dex-stage').value;renderDex()};$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.dexFilter=b.dataset.filter;state.dexGroup='all';groupOptions();renderDex()});
async function upsertCollection(id,patch,{open=true}={}){const cur=state.collection.get(id)||{user_id:state.user.id,tamagotchi_id:id,obtained:false,favorite:false,target:false};const row={...cur,...patch,user_id:state.user.id,tamagotchi_id:id};['id','created_at','updated_at'].forEach(k=>delete row[k]);const {data,error}=await supabase.from('user_tamagotchis').upsert(row,{onConflict:'user_id,tamagotchi_id'}).select().single();if(error)return toast(error.message);state.collection.set(id,data);renderAll();if(open)openTama(id)}
function openTama(id){const t=state.catalog.find(x=>x.id===id);if(!t)return;const c=state.collection.get(id);$('#tama-dialog-content').innerHTML=`<div class="tama-detail-head">${tamaImageMarkup(t,'detail-image')}<p class="eyebrow detail-eyebrow">${editionLabel(t.edition)} · ${esc(groupLabel(t))}</p><h2>${esc(displayName(t))}</h2><div class="detail-tags">${t.stage?`<span class="badge">${esc(t.stage)}</span>`:''}${t.family?`<span class="badge soft">${esc(t.family)}</span>`:''}</div></div><div class="detail-actions"><button id="toggle-owned" class="secondary ${c?.obtained?'active':''}">${c?.obtained?'✅ Obtenu':'○ Je l’ai obtenu'}</button><button id="toggle-target" class="secondary ${c?.target?'active':''}">${c?.target?'🎯 Objectif':'☆ Ajouter aux objectifs'}</button></div><button id="start-from-tama" class="primary full">🌱 Démarrer un élevage vers ${esc(displayName(t))}</button>${conditions(t)?`<div class="detail-block obtain"><h3>🧭 Comment l’obtenir</h3><div class="static-guide">${guideMarkup(t,'__preview__')}</div></div>`:''}${description(t)?`<div class="detail-block"><h3>À propos</h3><p>${esc(description(t))}</p></div>`:''}<a class="wiki-source" href="${wikiPageUrl(t)}" target="_blank" rel="noopener noreferrer">Voir la fiche source ↗</a>`;$('#tama-dialog').showModal();$('#toggle-owned').onclick=()=>upsertCollection(id,{obtained:!c?.obtained,first_obtained_at:!c?.obtained?new Date().toISOString().slice(0,10):c?.first_obtained_at||null});$('#toggle-target').onclick=()=>upsertCollection(id,{target:!c?.target});$('#start-from-tama').onclick=()=>{if(!state.schemaReady)return toast('Exécute d’abord la migration V3.2 dans Supabase.');$('#tama-dialog').close();openRaisingDialog(id)}}

function toggleParadiseEggFields(){const isP=$('#egg-edition').value==='paradise';$('#paradise-egg-fields')?.classList.toggle('hidden',!isP)}
function openEggDialog(rid=null){const f=$('#egg-form');f.reset();$('#egg-raising-id').value=rid||'';if(rid){const r=state.raisings.find(x=>x.id===rid),ctx=raisingContext(r);if(r){$('#egg-edition').value=raisingEdition(r);$('#egg-device').value=r.device_label||'';$('#egg-generation').value=ctx.generation||'';$('#egg-origin').value=ctx.marriage_origin||'';$('#egg-sex').value=ctx.sex||'';$('#egg-shell').value=ctx.shell||'';$('#egg-field').value=ctx.field||''}}toggleParadiseEggFields();$('#egg-dialog').showModal()}
function evolutionCandidates(r){
  const ed=raisingEdition(r),cur=currentTama(r),currentId=cur?.id||r.current_tamagotchi_id,currentStage=stageKey(r.current_stage||cur?.stage||'egg'),next=nextStage(currentStage);
  if(!next)return [];
  let ids=currentId?state.evolutionEdges.filter(e=>e.from_tamagotchi_id===currentId&&e.edition===ed).map(e=>e.to_tamagotchi_id):[];
  let rows=ids.length?state.catalog.filter(t=>ids.includes(t.id)):state.catalog.filter(t=>t.edition===ed&&stageKey(t.stage)===next);
  const sex=raisingContext(r).sex||cur?.gender;if(sex&&ed==='uni')rows=rows.filter(t=>!t.gender||t.gender===sex);
  return rows.sort((a,b)=>displayName(a).localeCompare(displayName(b),'fr'));
}
function openEvolutionDialog(rid){const r=state.raisings.find(x=>x.id===rid);if(!r)return;$('#evolution-raising-id').value=rid;$('#evolution-name').value='';$('#evolution-stage').value='';const rows=evolutionCandidates(r),isEgg=stageKey(r.current_stage)==='egg';$('#evolution-picker-title').textContent=isEgg?'🐣 Mon œuf a éclos !':'✨ À quoi ressemble ton nouveau Tama ?';$('#evolution-picker-help').textContent=rows.length?'Touche son image. Le nom et le stade seront enregistrés automatiquement.':'Aucune branche vérifiée trouvée : tu peux utiliser la saisie manuelle.';$('#evolution-candidates').innerHTML=rows.length?rows.map(t=>`<button type="button" class="evolution-choice" data-evolution-choice="${t.id}" data-raising-id="${rid}">${tamaImageMarkup(t,'evolution-choice-image')}<b>${esc(displayName(t))}</b><span>${stageLabel(t.stage)}${t.gender?` · ${t.gender==='female'?'♀':'♂'}`:''}</span><small>C’est lui/elle !</small></button>`).join(''):'<div class="empty-state">🤔 Aucun candidat illustré pour cette branche.</div>';$('#evolution-dialog').showModal();setTimeout(()=>batchResolveImages({showProgress:false}),0)}
function openPickTarget(rid){const r=state.raisings.find(x=>x.id===rid);if(!r)return;$('#pick-target-raising-id').value=rid;const ed=raisingEdition(r);[...$('#pick-target-select').options].forEach(o=>{const t=state.catalog.find(x=>x.id===o.value);o.hidden=!!t&&t.edition!==ed});const first=[...$('#pick-target-select').options].find(o=>!o.hidden);if(first)$('#pick-target-select').value=first.value;$('#pick-target-dialog').showModal()}
async function chooseTarget(rid,tid){const t=state.catalog.find(x=>x.id===tid);if(!t)return;const {error}=await supabase.from('active_raisings').update({target_tamagotchi_id:tid,mode:'target',edition:t.edition}).eq('id',rid);if(error)return toast(error.message);$('#pick-target-dialog')?.close();await loadV3();renderRaisings();toast(`${displayName(t)} devient ton objectif 🎯`)}

$('#evolution-none').onclick=()=>{$('.manual-evolution').open=true;$('#evolution-name').focus();toast('Tu peux saisir le nom si tu le connais.');};
$('#new-raising-btn').onclick=()=>{if(!state.schemaReady)return toast('Exécute d’abord la migration V3.2 dans Supabase.');$('#raising-mode-dialog').showModal()};
$('#raising-target').addEventListener('change',()=>{const t=state.catalog.find(x=>x.id===$('#raising-target').value);if(t)renderRaisingContextForm(t,{})});
$('#raising-form').addEventListener('submit',async e=>{e.preventDefault();const rid=$('#raising-id').value,context=collectContext(),t=state.catalog.find(x=>x.id===$('#raising-target').value),payload={current_tama_name:$('#raising-current').value.trim()||null,device_label:$('#raising-device').value.trim()||null,context};let error;if(rid){({error}=await supabase.from('active_raisings').update(payload).eq('id',rid))}else{Object.assign(payload,{user_id:state.user.id,target_tamagotchi_id:$('#raising-target').value,mode:'target',edition:t?.edition||null});({error}=await supabase.from('active_raisings').insert(payload))}if(error)return toast(error.message);$('#raising-dialog').close();$('#raising-target').disabled=false;e.target.reset();await loadV3();renderRaisings();toast(rid?'Prérequis mis à jour ✓':'Élevage démarré 🌱')});
$('#egg-edition').addEventListener('change',toggleParadiseEggFields);
$('#egg-form').addEventListener('submit',async e=>{e.preventDefault();const rid=$('#egg-raising-id').value,edition=$('#egg-edition').value,context={};const gen=Number($('#egg-generation').value);if(gen)context.generation=gen;const origin=$('#egg-origin').value,sex=$('#egg-sex').value;if(origin)context.marriage_origin=origin;if(sex)context.sex=sex;if(edition==='paradise'){const shell=$('#egg-shell').value,field=$('#egg-field').value;if(shell)context.shell=shell;if(field)context.field=field}const base={edition,device_label:$('#egg-device').value.trim()||null,context};if(rid){const r=state.raisings.find(x=>x.id===rid);context.current_tama=r?.current_tama_name||undefined;const {error}=await supabase.from('active_raisings').update(base).eq('id',rid);if(error)return toast(error.message);$('#egg-dialog').close();await loadV3();renderRaisings();return toast('Informations mises à jour ✓')}const payload={...base,user_id:state.user.id,target_tamagotchi_id:null,mode:'discovery',current_tama_name:'Œuf',current_stage:'egg'};const {data,error}=await supabase.from('active_raisings').insert(payload).select().single();if(error)return toast(error.message);await supabase.from('raising_stage_events').insert({raising_id:data.id,user_id:state.user.id,tama_name:'Œuf',stage:'egg',note:'Début de l’élevage'});$('#egg-dialog').close();await loadV3();renderRaisings();toast('Nouvel œuf suivi 🥚')});
async function recordEvolution(rid,tama,manualName=null,manualStage=null){const r=state.raisings.find(x=>x.id===rid);if(!r)return;const name=tama?displayName(tama):manualName,stage=tama?stageKey(tama.stage):stageKey(manualStage),ctx={...raisingContext(r),current_tama:name};if(tama?.gender&&!ctx.sex)ctx.sex=tama.gender;const patch={current_tama_name:name,current_stage:stage||null,current_tamagotchi_id:tama?.id||null,context:ctx};if(stage==='adult'&&tama){patch.target_tamagotchi_id=tama.id;patch.mode='target'}const {error}=await supabase.from('active_raisings').update(patch).eq('id',rid);if(error)return toast(error.message);await supabase.from('raising_stage_events').insert({raising_id:rid,user_id:state.user.id,tama_name:name,stage:stage||null,tamagotchi_id:tama?.id||null});if(tama){const cur=state.collection.get(tama.id);await upsertCollection(tama.id,{obtained:true,first_obtained_at:cur?.first_obtained_at||new Date().toISOString().slice(0,10),last_obtained_at:new Date().toISOString().slice(0,10),obtained_count:Number(cur?.obtained_count||0)+1},{open:false});}$('#evolution-dialog').close();await loadV3();renderRaisings();toast(tama?`${displayName(tama)} ajouté à ta collection ✨`:`Évolution enregistrée : ${name} ✨`)}
$('#evolution-form').addEventListener('submit',async e=>{e.preventDefault();const rid=$('#evolution-raising-id').value,name=$('#evolution-name').value.trim(),stage=$('#evolution-stage').value;if(!name)return;const match=state.catalog.find(t=>t.edition===raisingEdition(state.raisings.find(r=>r.id===rid))&&[t.name,displayName(t)].some(v=>String(v).toLowerCase()===name.toLowerCase()));await recordEvolution(rid,match||null,name,stage)});
$('#pick-target-form').addEventListener('submit',async e=>{e.preventDefault();await chooseTarget($('#pick-target-raising-id').value,$('#pick-target-select').value)});
async function setHappiness(rid,value){const r=state.raisings.find(x=>x.id===rid);if(!r)return;const context={...raisingContext(r),happiness_points:value};const {error}=await supabase.from('active_raisings').update({context}).eq('id',rid);if(error)return toast(error.message);r.context=context;renderRaisings();toast(`Bonheur noté : ${value<=5?'0–5':value<=14?'6–14':'15–20'} ❤️`)}
async function setField(rid,value){const r=state.raisings.find(x=>x.id===rid);if(!r)return;const context={...raisingContext(r),field:value};const {error}=await supabase.from('active_raisings').update({context}).eq('id',rid);if(error)return toast(error.message);r.context=context;renderRaisings();toast(`Champ Paradise : ${value} 🌍`)}
async function logAction(rid,type){const {error}=await supabase.from('raising_actions').insert({raising_id:rid,user_id:state.user.id,action_type:type,label:tr('action',type,type),quantity:1});if(error)return toast(error.message);const {data}=await supabase.from('raising_actions').select('*').eq('user_id',state.user.id).order('created_at',{ascending:true});state.raisingActions=data||[];renderRaisings()}
async function completeRaising(rid){const r=state.raisings.find(x=>x.id===rid);if(!r)return;const t=r.target||state.catalog.find(x=>x.id===r.target_tamagotchi_id);if(!t)return toast('Choisis d’abord l’adulte obtenu.');if(!confirm(`Confirmer que tu as obtenu ${displayName(t)} ?`))return;await supabase.from('active_raisings').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',rid);await upsertCollection(r.target_tamagotchi_id,{obtained:true,target:false,first_obtained_at:new Date().toISOString().slice(0,10)});await loadV3();renderRaisings();$('#tama-dialog')?.close();toast(`${displayName(t)} ajouté à ta collection 🎉`)}
async function abandonRaising(rid){const r=state.raisings.find(x=>x.id===rid),t=r?.target||state.catalog.find(x=>x.id===r?.target_tamagotchi_id);const label=t?` vers ${displayName(t)}`:'';if(!confirm(`Arrêter cet élevage${label} ? Les actions et la chronologie restent archivées.`))return;await supabase.from('active_raisings').update({status:'abandoned',completed_at:new Date().toISOString()}).eq('id',rid);await loadV3();renderRaisings();toast('Élevage archivé')}

$('#profile-form').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await supabase.from('profiles').update({username:$('#profile-username').value.trim()||null,display_name:$('#profile-name').value.trim(),bio:$('#profile-bio').value.trim(),collection_public:$('#profile-public').checked}).eq('id',state.user.id).select().single();if(error)return toast(error.code==='23505'?'Ce pseudo est déjà utilisé.':error.message);state.profile=data;await loadProfile();toast('Profil enregistré ✨')});
$('#friend-search-btn').onclick=async()=>{const q=$('#friend-search').value.trim();if(!q)return;const {data,error}=await supabase.from('profiles').select('id,username,display_name').neq('id',state.user.id).or(`username.eq.${q},display_name.ilike.%${q}%`).limit(10);if(error)return toast(error.message);$('#friend-results').innerHTML=(data||[]).length?data.map(p=>`<div class="list-card"><div class="grow"><h3>${esc(p.display_name||p.username||'Collectionneuse')}</h3><p>@${esc(p.username||'sans-pseudo')}</p></div><button class="icon-btn" data-add-friend="${p.id}">＋</button></div>`).join(''):'<p class="muted">Aucun profil trouvé.</p>'};
$('#new-challenge-btn').onclick=()=>$('#challenge-dialog').showModal();$('#challenge-type').onchange=()=>{const type=$('#challenge-type').value;$('#challenge-tama-wrap').classList.toggle('hidden',type!=='specific_tama');$('#challenge-count-wrap').classList.toggle('hidden',!['collect_count','cooperative_count'].includes(type))};
$('#challenge-form').addEventListener('submit',async e=>{e.preventDefault();const type=$('#challenge-type').value,end=$('#challenge-end').value,payload={creator_id:state.user.id,title:$('#challenge-title').value.trim(),description:$('#challenge-description').value.trim()||null,challenge_type:type,target_tamagotchi_id:type==='specific_tama'?$('#challenge-tama').value:null,target_count:['collect_count','cooperative_count'].includes(type)?Number($('#challenge-count').value):null,ends_at:end?new Date(`${end}T23:59:59`).toISOString():null};const {data,error}=await supabase.from('challenges').insert(payload).select().single();if(error)return toast(error.message);await supabase.from('challenge_participants').insert({challenge_id:data.id,user_id:state.user.id,status:'accepted'});$('#challenge-dialog').close();e.target.reset();await loadChallenges();renderChallenges();toast('Défi créé 🏆')});

$('#admin-tama-search').oninput=renderAdmin;$('#admin-tama-select').onchange=()=>{state.adminTamaId=$('#admin-tama-select').value;fillAdminTama()};['admin-name-fr','admin-image-url','admin-image-scale','admin-image-x','admin-image-y'].forEach(id=>$('#'+id).addEventListener('input',updateAdminPreview));
$('#admin-tama-form').addEventListener('submit',async e=>{e.preventDefault();if(!state.isAdmin)return;const id=state.adminTamaId;let rules=null;const rawRules=$('#admin-rules-json').value.trim();if(rawRules){try{rules=JSON.parse(rawRules)}catch{return toast('Le JSON des règles structurées est invalide.')}}const payload={name_fr:$('#admin-name-fr').value.trim()||null,description_fr:$('#admin-description-fr').value.trim()||null,evolution_conditions_fr:$('#admin-conditions-fr').value.trim()||null,evolution_rules:rules,rules_verified:$('#admin-rules-verified').checked,rules_source_url:$('#admin-rules-source').value.trim()||null,image_url:$('#admin-image-url').value.trim()||null,image_scale:Number($('#admin-image-scale').value)/100,image_pos_x:Number($('#admin-image-x').value),image_pos_y:Number($('#admin-image-y').value)};const {data,error}=await supabase.from('tamagotchis').update(payload).eq('id',id).select().single();if(error)return toast(error.message);const i=state.catalog.findIndex(t=>t.id===id);state.catalog[i]=data;if(data.image_url)setCachedImage(data,data.image_url);renderAll();toast('Personnage enregistré ✨')});
$('#translation-search').oninput=renderTranslations;$('#translations-list').addEventListener('change',async e=>{const input=e.target.closest('[data-translation-id]');if(!input)return;const row=state.translations.find(x=>x.id===input.dataset.translationId);if(!row)return;const {data,error}=await supabase.from('app_translations').update({value_fr:input.value.trim()}).eq('id',row.id).select().single();if(error)return toast(error.message);Object.assign(row,data);state.translationMap.set(`${row.category}:${row.key}`,row.value_fr);renderRaisings();toast('Traduction enregistrée')});
$('#resolve-images-btn').onclick=async()=>{if(!state.isAdmin)return;toast('Résolution des illustrations…');await batchResolveImages({persist:true,showProgress:true});renderAdmin()};

supabase.auth.onAuthStateChange(async(_event,session)=>{state.user=session?.user||null;if(state.user){$('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');await bootstrap()}else{$('#app-view').classList.add('hidden');$('#auth-view').classList.remove('hidden')}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));
